// src/pages/marketplace/MarketplacePage.tsx
import { useState, useMemo, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Search } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { ListingGrid } from '@/features/classifieds/components/ListingGrid';
import { CategorySection } from '@/features/classifieds/components/CategorySection';
import { FilterButton } from '@/features/classifieds/components/FilterButton';
import { useListings } from '@/features/classifieds/hooks/useListings';
import { NDKClassified } from '@nostr-dev-kit/ndk';

const CATEGORIES = [
  { value: '', label: 'All Categories' },
  { value: 'electronics', label: 'Electronics' },
  { value: 'furniture', label: 'Furniture' },
  { value: 'clothing', label: 'Clothing' },
  { value: 'books', label: 'Books' },
  { value: 'services', label: 'Services' },
  { value: 'vehicles', label: 'Vehicles' },
  { value: 'real-estate', label: 'Real Estate' },
  { value: 'jobs', label: 'Jobs' },
  { value: 'free', label: 'Free' },
  { value: 'wanted', label: 'Wanted' }
];

export function MarketplacePage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const [selectedCategory, setSelectedCategory] = useState(searchParams.get('category') || '');
  const [searchQuery, setSearchQuery] = useState('');

  const { listings } = useListings({
    category: selectedCategory || undefined
  });

  // Update URL when category changes
  useEffect(() => {
    if (selectedCategory) {
      setSearchParams({ category: selectedCategory });
    } else {
      setSearchParams({});
    }
  }, [selectedCategory, setSearchParams]);

  // Filter and group listings
  const { filteredListings, listingsByCategory } = useMemo(() => {
    // First filter by search query
    const filtered = listings.filter(listing => {
      if (!searchQuery) return true;
      const query = searchQuery.toLowerCase();
      return (
        listing.title.toLowerCase().includes(query) ||
        listing.summary?.toLowerCase().includes(query) ||
        listing.content.toLowerCase().includes(query) ||
        listing.location?.toLowerCase().includes(query)
      );
    });

    // Group by category for the category sections view
    const byCategory = filtered.reduce<Record<string, NDKClassified[]>>((acc, listing) => {
      const categories = listing.tags.filter(t => t[0] === 't').map(t => t[1]);
      if (categories.length > 0) {
        categories.forEach(category => {
          const key = category.toLowerCase();
          if (!acc[key]) acc[key] = [];
          acc[key].push(listing);
        });
      } else {
        if (!acc['uncategorized']) acc['uncategorized'] = [];
        acc['uncategorized'].push(listing);
      }
      return acc;
    }, {});

    return { filteredListings: filtered, listingsByCategory: byCategory };
  }, [listings, searchQuery]);

  // Determine view mode
  const isFilteredView = selectedCategory || searchQuery;

  return (
    <div className="min-h-screen bg-neutral-50 dark:bg-black">
      <div className="container mx-auto px-4 py-4 max-w-7xl">
        {/* Header */}
        <div className="mb-6">
          <h1 className="text-2xl sm:text-3xl font-bold bg-gradient-to-r from-primary-600 to-primary-400 bg-clip-text text-transparent mb-4">
            Marketplace
          </h1>

          {/* Search and Filter Bar */}
          <div className="flex gap-2 sm:gap-3">
            <div className="flex-1">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-neutral-400 w-5 h-5 pointer-events-none" />
                <Input
                  placeholder="Search listings..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10 h-12 bg-white/80 dark:bg-black/80 backdrop-blur border-neutral-200 dark:border-neutral-700 rounded-xl text-base focus:ring-2 focus:ring-primary-500/20 focus:border-primary-500 transition-all"
                />
              </div>
            </div>

            <FilterButton
              categories={CATEGORIES}
              selectedCategory={selectedCategory}
              onCategoryChange={setSelectedCategory}
            />
          </div>
        </div>

        {/* Content */}
        {isFilteredView ? (
          // Filtered view - show grid
          <div>
            {selectedCategory && (
              <div className="mb-6">
                <h2 className="text-xl font-semibold text-neutral-900 dark:text-white">
                  {CATEGORIES.find(c => c.value === selectedCategory)?.label || selectedCategory}
                </h2>
                <p className="text-sm text-neutral-500 dark:text-neutral-400 mt-1">
                  {filteredListings.length} listings found
                </p>
              </div>
            )}
            <ListingGrid listings={filteredListings} />
          </div>
        ) : (
          // Category sections view
          <div>
            {Object.keys(listingsByCategory).length === 0 ? (
              <ListingGrid listings={[]} />
            ) : (
              <>
                {/* Featured/Recent listings */}
                {listings.length > 0 && (
                  <CategorySection
                    category="Recent Listings"
                    listings={listings.slice(0, 10)}
                    showViewAll={false}
                  />
                )}

                {/* Category sections */}
                {CATEGORIES.filter(c => c.value && listingsByCategory[c.value]?.length > 0).map(category => (
                  <CategorySection
                    key={category.value}
                    category={category.value}
                    listings={listingsByCategory[category.value]}
                  />
                ))}

                {/* Uncategorized section */}
                {listingsByCategory['uncategorized']?.length > 0 && (
                  <CategorySection
                    category="Other"
                    listings={listingsByCategory['uncategorized']}
                    showViewAll={false}
                  />
                )}
              </>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// src/lib/pages/MarketplacePage.svelte
<script lang="ts">
  import { ndk } from '$lib/ndk.svelte';
  import { NDKKind, NDKEvent } from '@nostr-dev-kit/ndk';
  import type { NDKFilter } from '@nostr-dev-kit/ndk';
  import { goto } from '$app/navigation';

  const CATEGORIES = [
    { value: '', label: 'All Categories' },
    { value: 'electronics', label: 'Electronics' },
    { value: 'furniture', label: 'Furniture' },
    { value: 'clothing', label: 'Clothing' },
    { value: 'books', label: 'Books' },
    { value: 'services', label: 'Services' },
    { value: 'vehicles', label: 'Vehicles' },
    { value: 'real-estate', label: 'Real Estate' },
    { value: 'jobs', label: 'Jobs' },
    { value: 'free', label: 'Free' },
    { value: 'wanted', label: 'Wanted' }
  ];

  let selectedCategory = $state('');
  let searchQuery = $state('');

  // Subscribe to classifieds with reactive filters
  const subscription = ndk.$subscribe(() => {
    const filter: NDKFilter = {
      kinds: [30402 as NDKKind], // NDKKind.Classified
      limit: 50
    };

    if (selectedCategory) {
      filter['#t'] = [selectedCategory.toLowerCase()];
    }

    return {
      filters: [filter],
      bufferMs: 100,
    };
  });

  // Filter and process listings
  const listings = $derived.by(() => {
    return subscription.events
      .filter(event => {
        const status = event.tagValue('status') || 'active';
        if (status !== 'active') return false;

        if (!searchQuery) return true;

        const query = searchQuery.toLowerCase();
        const title = event.tagValue('title')?.toLowerCase() || '';
        const summary = event.tagValue('summary')?.toLowerCase() || '';
        const content = event.content?.toLowerCase() || '';
        const location = event.tagValue('location')?.toLowerCase() || '';

        return title.includes(query) ||
               summary.includes(query) ||
               content.includes(query) ||
               location.includes(query);
      });
  });

  // Group listings by category
  const listingsByCategory = $derived.by(() => {
    const grouped: Record<string, NDKEvent[]> = {};

    listings.forEach(listing => {
      const categories = listing.tags.filter(t => t[0] === 't').map(t => t[1]);
      if (categories.length > 0) {
        categories.forEach(category => {
          const key = category.toLowerCase();
          if (!grouped[key]) grouped[key] = [];
          grouped[key].push(listing);
        });
      } else {
        if (!grouped['uncategorized']) grouped['uncategorized'] = [];
        grouped['uncategorized'].push(listing);
      }
    });

    return grouped;
  });

  const isFilteredView = $derived(selectedCategory || searchQuery);

  function handleCategoryChange(category: string) {
    selectedCategory = category;
  }

  function getListingImage(listing: NDKEvent): string | undefined {
    return listing.tagValue('image');
  }

  function getListingPrice(listing: NDKEvent): { amount: string; currency: string } | null {
    const priceTag = listing.tags.find(t => t[0] === 'price');
    if (!priceTag || !priceTag[1] || !priceTag[2]) return null;
    return {
      amount: priceTag[1],
      currency: priceTag[2]
    };
  }
</script>

<div class="min-h-screen bg-neutral-50 dark:bg-black">
  <div class="container mx-auto px-4 py-4 max-w-7xl">
    <!-- Header -->
    <div class="mb-6">
      <h1 class="text-2xl sm:text-3xl font-bold bg-gradient-to-r from-primary-600 to-primary-400 bg-clip-text text-transparent mb-4">
        Marketplace
      </h1>

      <!-- Search and Filter Bar -->
      <div class="flex gap-2 sm:gap-3">
        <div class="flex-1">
          <div class="relative">
            <svg class="absolute left-3 top-1/2 transform -translate-y-1/2 text-neutral-400 w-5 h-5 pointer-events-none" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
            <input
              type="text"
              placeholder="Search listings..."
              bind:value={searchQuery}
              class="w-full pl-10 h-12 bg-white/80 dark:bg-black/80 backdrop-blur border border-neutral-200 dark:border-neutral-700 rounded-xl text-base focus:ring-2 focus:ring-primary-500/20 focus:border-primary-500 transition-all"
            />
          </div>
        </div>

        <!-- Category Filter -->
        <div class="relative">
          <select
            bind:value={selectedCategory}
            class="h-12 px-4 bg-white/80 dark:bg-black/80 backdrop-blur border border-neutral-200 dark:border-neutral-700 rounded-xl text-base focus:ring-2 focus:ring-primary-500/20 focus:border-primary-500 transition-all appearance-none pr-10"
          >
            {#each CATEGORIES as category}
              <option value={category.value}>{category.label}</option>
            {/each}
          </select>
          <svg class="absolute right-3 top-1/2 transform -translate-y-1/2 text-neutral-400 w-5 h-5 pointer-events-none" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
          </svg>
        </div>
      </div>
    </div>

    <!-- Content -->
    {#if isFilteredView}
      <!-- Filtered view - show grid -->
      <div>
        {#if selectedCategory}
          <div class="mb-6">
            <h2 class="text-xl font-semibold text-neutral-900 dark:text-white">
              {CATEGORIES.find(c => c.value === selectedCategory)?.label || selectedCategory}
            </h2>
            <p class="text-sm text-neutral-500 dark:text-neutral-400 mt-1">
              {listings.length} listings found
            </p>
          </div>
        {/if}

        <!-- Listings Grid -->
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
          {#each listings as listing (listing.id)}
            {@const price = getListingPrice(listing)}
            <button
              onclick={() => goto(`/marketplace/${listing.encode()}`)}
              class="bg-white dark:bg-neutral-900/50 rounded-xl border border-neutral-200 dark:border-neutral-800/50 overflow-hidden transition-all hover:border-primary-500 dark:hover:border-primary-500 hover:shadow-lg text-left"
            >
              {#if getListingImage(listing)}
                <div class="aspect-video bg-neutral-100 dark:bg-neutral-800 overflow-hidden">
                  <img
                    src={getListingImage(listing)}
                    alt={listing.tagValue('title') || 'Listing'}
                    class="w-full h-full object-cover"
                  />
                </div>
              {/if}
              <div class="p-4">
                <h3 class="font-semibold text-neutral-900 dark:text-white truncate">
                  {listing.tagValue('title') || 'Untitled'}
                </h3>
                {#if listing.tagValue('summary')}
                  <p class="text-sm text-neutral-500 dark:text-neutral-400 mt-1 line-clamp-2">
                    {listing.tagValue('summary')}
                  </p>
                {/if}
                {#if price}
                  <p class="text-sm font-medium text-primary-600 dark:text-primary-400 mt-2">
                    {price.amount} {price.currency}
                  </p>
                {/if}
              </div>
            </button>
          {:else}
            <div class="col-span-full text-center py-12 text-neutral-500 dark:text-neutral-400">
              No listings found
            </div>
          {/each}
        </div>
      </div>
    {:else}
      <!-- Category sections view -->
      <div>
        {#if Object.keys(listingsByCategory).length === 0}
          <div class="text-center py-12 text-neutral-500 dark:text-neutral-400">
            No marketplace items yet
          </div>
        {:else}
          <!-- Recent listings -->
          {#if listings.length > 0}
            <div class="mb-8">
              <h2 class="text-xl font-semibold text-neutral-900 dark:text-white mb-4">
                Recent Listings
              </h2>
              <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
                {#each listings.slice(0, 8) as listing (listing.id)}
                  {@const price = getListingPrice(listing)}
                  <button
                    onclick={() => goto(`/marketplace/${listing.encode()}`)}
                    class="bg-white dark:bg-neutral-900/50 rounded-xl border border-neutral-200 dark:border-neutral-800/50 overflow-hidden transition-all hover:border-primary-500 dark:hover:border-primary-500 hover:shadow-lg text-left"
                  >
                    {#if getListingImage(listing)}
                      <div class="aspect-video bg-neutral-100 dark:bg-neutral-800 overflow-hidden">
                        <img
                          src={getListingImage(listing)}
                          alt={listing.tagValue('title') || 'Listing'}
                          class="w-full h-full object-cover"
                        />
                      </div>
                    {/if}
                    <div class="p-4">
                      <h3 class="font-semibold text-neutral-900 dark:text-white truncate">
                        {listing.tagValue('title') || 'Untitled'}
                      </h3>
                      {#if listing.tagValue('summary')}
                        <p class="text-sm text-neutral-500 dark:text-neutral-400 mt-1 line-clamp-2">
                          {listing.tagValue('summary')}
                        </p>
                      {/if}
                      {#if price}
                        <p class="text-sm font-medium text-primary-600 dark:text-primary-400 mt-2">
                          {price.amount} {price.currency}
                        </p>
                      {/if}
                    </div>
                  </button>
                {/each}
              </div>
            </div>
          {/if}

          <!-- Category sections -->
          {#each CATEGORIES.filter(c => c.value && listingsByCategory[c.value]?.length > 0) as category}
            <div class="mb-8">
              <div class="flex items-center justify-between mb-4">
                <h2 class="text-xl font-semibold text-neutral-900 dark:text-white">
                  {category.label}
                </h2>
                <button
                  onclick={() => handleCategoryChange(category.value)}
                  class="text-sm text-primary-600 dark:text-primary-400 hover:underline"
                >
                  View All
                </button>
              </div>
              <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
                {#each listingsByCategory[category.value].slice(0, 4) as listing (listing.id)}
                  {@const price = getListingPrice(listing)}
                  <button
                    onclick={() => goto(`/marketplace/${listing.encode()}`)}
                    class="bg-white dark:bg-neutral-900/50 rounded-xl border border-neutral-200 dark:border-neutral-800/50 overflow-hidden transition-all hover:border-primary-500 dark:hover:border-primary-500 hover:shadow-lg text-left"
                  >
                    {#if getListingImage(listing)}
                      <div class="aspect-video bg-neutral-100 dark:bg-neutral-800 overflow-hidden">
                        <img
                          src={getListingImage(listing)}
                          alt={listing.tagValue('title') || 'Listing'}
                          class="w-full h-full object-cover"
                        />
                      </div>
                    {/if}
                    <div class="p-4">
                      <h3 class="font-semibold text-neutral-900 dark:text-white truncate">
                        {listing.tagValue('title') || 'Untitled'}
                      </h3>
                      {#if listing.tagValue('summary')}
                        <p class="text-sm text-neutral-500 dark:text-neutral-400 mt-1 line-clamp-2">
                          {listing.tagValue('summary')}
                        </p>
                      {/if}
                      {#if price}
                        <p class="text-sm font-medium text-primary-600 dark:text-primary-400 mt-2">
                          {price.amount} {price.currency}
                        </p>
                      {/if}
                    </div>
                  </button>
                {/each}
              </div>
            </div>
          {/each}
        {/if}
      </div>
    {/if}
  </div>
</div>
