// src/lib/components/ArticleList.svelte
<script lang="ts">
  import type { NDKArticle } from '@nostr-dev-kit/ndk';
  import ArticlePreviewCard from './ArticlePreviewCard.svelte';

  interface Props {
    articles: NDKArticle[];
    isLoading?: boolean;
    emptyMessage?: string;
  }

  const { articles, isLoading = false, emptyMessage = 'No articles yet' }: Props = $props();
</script>

{#if isLoading}
  <div class="text-center py-8 text-neutral-400">
    <svg class="w-8 h-8 animate-spin mx-auto mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
    </svg>
    <p>Loading articles...</p>
  </div>
{:else if articles.length === 0}
  <div class="text-center py-8 text-neutral-400">
    {emptyMessage}
  </div>
{:else}
  <div class="divide-y divide-neutral-800/50">
    {#each articles as article (article.id)}
      <ArticlePreviewCard {article} />
    {/each}
  </div>
{/if}

// src/features/articles/components/ArticleList.tsx
import { NDKArticle } from '@nostr-dev-kit/ndk';
import { ArticlePreviewCard } from './ArticlePreviewCard';
interface ArticleListProps {
  articles: NDKArticle[];
  variant?: 'default' | 'compact';
  emptyMessage?: string;
}
export function ArticleList({ 
  articles, 
  variant = 'default',
  emptyMessage = 'No articles found'
}: ArticleListProps) {
  if (articles.length === 0) {
    return (
      <div className="text-center py-12 text-neutral-500 dark:text-neutral-400">
        {emptyMessage}
      </div>
    );
  }
  return (
    <div>
      {articles.map((article) => (
        <ArticlePreviewCard 
          key={article.id} 
          article={article} 
          variant={variant}
        />
      ))}
    </div>
  );
}
