// src/lib/components/RelaySelector.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { settings } from '$lib/stores/settings.svelte';
  import { relayFilter } from '$lib/stores/relayFilter.svelte';
  import { useRelayInfoCached } from '$lib/utils/relayInfo.svelte';
  import { clickOutside } from '$lib/utils/clickOutside';

  interface Props {
    active?: boolean;
  }

  const { active = false }: Props = $props();

  let isOpen = $state(false);
  let enabledRelays = $derived(settings.relays.filter(r => r.enabled && r.read));

  const selectedRelayInfo = $derived.by(() => {
    if (!relayFilter.selectedRelay) return null;
    return useRelayInfoCached(relayFilter.selectedRelay);
  });

  const displayName = $derived.by(() => {
    if (relayFilter.selectedRelay && selectedRelayInfo?.info?.name) {
      return selectedRelayInfo.info.name;
    }
    if (relayFilter.selectedRelay) {
      return relayFilter.selectedRelay.replace('wss://', '').replace('ws://', '');
    }
    return 'Following';
  });

  function handleClick() {
    if (active) {
      // On home page: toggle dropdown
      isOpen = !isOpen;
    } else {
      // Not on home page: navigate to home
      goto('/');
    }
  }

  function selectRelay(url: string) {
    relayFilter.selectedRelay = url;
    isOpen = false;
  }

  function selectFollowing() {
    relayFilter.selectedRelay = null;
    isOpen = false;
  }

  function handleClickOutside() {
    isOpen = false;
  }
</script>

<div class="relative" use:clickOutside={handleClickOutside}>
  <!-- Navigation Button -->
  <button
    onclick={handleClick}
    class="flex items-center gap-3 px-4 py-3 rounded-lg transition-colors w-full {active ? 'text-orange-500 bg-orange-500/10' : 'text-neutral-300 hover:bg-neutral-800/50'}"
  >
    <!-- Icon - changes based on selection -->
    {#if relayFilter.selectedRelay && selectedRelayInfo?.info?.icon}
      <img src={selectedRelayInfo.info.icon} alt="" class="w-6 h-6 rounded flex-shrink-0" />
    {:else if relayFilter.selectedRelay}
      <div class="w-6 h-6 rounded bg-orange-500 flex items-center justify-center flex-shrink-0">
        <svg class="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01" />
        </svg>
      </div>
    {:else}
      <!-- Users icon for "Following" -->
      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
      </svg>
    {/if}

    <span class="font-medium flex-1 text-left">{displayName}</span>

    <!-- Chevron -->
    <svg
      class="w-4 h-4 transition-transform {isOpen ? 'rotate-180' : ''}"
      fill="none"
      stroke="currentColor"
      viewBox="0 0 24 24"
    >
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
    </svg>
  </button>

  <!-- Dropdown Menu - only show when on home page -->
  {#if isOpen && active}
    <div class="absolute left-0 mt-1 w-full bg-neutral-900 border border-neutral-800 rounded-lg shadow-xl z-50 overflow-hidden">
      <!-- Following option -->
      <button
        onclick={selectFollowing}
        class="w-full px-4 py-3 hover:bg-neutral-800 transition-colors text-left flex items-center gap-3 {!relayFilter.selectedRelay ? 'bg-neutral-800/50' : ''}"
      >
        <svg class="w-5 h-5 text-neutral-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
        </svg>
        <div class="flex-1">
          <div class="font-medium text-white">Following</div>
          <div class="text-xs text-neutral-500">All posts from people you follow</div>
        </div>
        {#if !relayFilter.selectedRelay}
          <svg class="w-5 h-5 text-orange-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
          </svg>
        {/if}
      </button>

      <!-- Divider -->
      <div class="border-t border-neutral-800 my-1"></div>

      <!-- Relay options -->
      <div class="px-2 py-1">
        <div class="text-xs text-neutral-500 px-2 py-1 font-medium">Filter by Relay</div>
        {#each enabledRelays as relay (relay.url)}
          {@const relayInfo = useRelayInfoCached(relay.url)}
          <button
            onclick={() => selectRelay(relay.url)}
            class="w-full px-3 py-2.5 rounded-lg hover:bg-neutral-800 transition-colors text-left flex items-center gap-3 {relayFilter.selectedRelay === relay.url ? 'bg-neutral-800/50' : ''}"
          >
            {#if relayInfo.info?.icon}
              <img src={relayInfo.info.icon} alt="" class="w-5 h-5 rounded flex-shrink-0" />
            {:else}
              <div class="w-5 h-5 rounded bg-neutral-700 flex items-center justify-center flex-shrink-0">
                <svg class="w-3 h-3 text-neutral-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01" />
                </svg>
              </div>
            {/if}
            <div class="flex-1 min-w-0">
              <div class="text-sm font-medium text-white truncate">
                {relayInfo.info?.name || relay.url.replace('wss://', '').replace('ws://', '')}
              </div>
              {#if relayInfo.info?.description}
                <div class="text-xs text-neutral-500 truncate">
                  {relayInfo.info.description}
                </div>
              {/if}
            </div>
            {#if relayFilter.selectedRelay === relay.url}
              <svg class="w-5 h-5 text-orange-500 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
              </svg>
            {/if}
          </button>
        {/each}
      </div>

      <!-- Manage relays link -->
      <div class="border-t border-neutral-800 mt-1">
        <a
          href="/settings"
          class="block w-full px-4 py-2.5 text-sm text-center text-orange-500 hover:bg-neutral-800 transition-colors"
          onclick={() => isOpen = false}
        >
          Manage Relays →
        </a>
      </div>
    </div>
  {/if}
</div>

// src/components/navigation/RelaySelector.tsx
import { ChevronDown, Globe, Circle, Check } from "lucide-react";
import { useState, useRef, useEffect } from "react";
import { useSettingsStore } from "@/stores/settingsStore";
import { useNavigate } from "react-router-dom";

export function RelaySelector() {
  const [isOpen, setIsOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const navigate = useNavigate();

  const { relays, selectedRelay, setSelectedRelay } = useSettingsStore();
  const enabledRelays = relays.filter(r => r.enabled);

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };

    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  const handleRelaySelect = (relayUrl: string | null) => {
    setSelectedRelay(relayUrl);
    setIsOpen(false);
  };

  const getRelayDisplayName = (url: string) => {
    try {
      const urlObj = new URL(url);
      return urlObj.hostname.replace("wss://", "").replace("ws://", "");
    } catch {
      return url.replace("wss://", "").replace("ws://", "");
    }
  };

  const currentRelayDisplay = selectedRelay
    ? getRelayDisplayName(selectedRelay)
    : `All Relays (${enabledRelays.length})`;

  return (
    <div className="relative" ref={dropdownRef}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-1.5 px-2 py-1 text-sm text-gray-600 dark:text-gray-400
                   hover:text-gray-900 dark:hover:text-gray-100 transition-colors"
      >
        <Globe className="h-4 w-4" />
        <span className="max-w-[140px] truncate font-normal">{currentRelayDisplay}</span>
        <ChevronDown className={`h-3 w-3 transition-transform ${isOpen ? 'rotate-180' : ''}`} />
      </button>

      {isOpen && (
        <div className="absolute top-full mt-2 right-0 w-64 bg-white dark:bg-black rounded-lg shadow-lg
                        border border-gray-200 dark:border-gray-700 overflow-hidden z-50">
          <div className="py-1">
            {/* All Relays option */}
            <button
              onClick={() => handleRelaySelect(null)}
              className="w-full flex items-center justify-between px-4 py-2 text-sm text-gray-700 dark:text-gray-200
                         hover:bg-gray-100 dark:hover:bg-neutral-900 transition-colors"
            >
              <div className="flex items-center gap-2">
                <Globe className="h-4 w-4 text-blue-500" />
                <span>All Relays ({enabledRelays.length})</span>
              </div>
              {!selectedRelay && <Check className="h-4 w-4 text-green-500" />}
            </button>

            {/* Divider */}
            <div className="h-px bg-gray-200 dark:bg-black my-1" />

            {/* Individual relays */}
            {enabledRelays.length > 0 ? (
              enabledRelays.map((relay) => (
                <button
                  key={relay.url}
                  onClick={() => handleRelaySelect(relay.url)}
                  className="w-full flex items-center justify-between px-4 py-2 text-sm text-gray-700 dark:text-gray-200
                             hover:bg-gray-100 dark:hover:bg-neutral-900 transition-colors"
                >
                  <div className="flex items-center gap-2">
                    <Circle
                      className={`h-2 w-2 ${relay.write && relay.read ? 'fill-green-500 text-green-500' :
                                             relay.read ? 'fill-blue-500 text-blue-500' :
                                             'fill-orange-500 text-orange-500'}`}
                    />
                    <span className="truncate">{getRelayDisplayName(relay.url)}</span>
                  </div>
                  {selectedRelay === relay.url && <Check className="h-4 w-4 text-green-500" />}
                </button>
              ))
            ) : (
              <div className="px-4 py-3 text-sm text-gray-500 dark:text-gray-400">
                No relays enabled
              </div>
            )}

            {/* Divider */}
            <div className="h-px bg-gray-200 dark:bg-black my-1" />

            {/* Settings link */}
            <button
              onClick={() => {
                setIsOpen(false);
                navigate('/settings');
              }}
              className="w-full flex items-center px-4 py-2 text-sm text-blue-600 dark:text-blue-400
                         hover:bg-gray-100 dark:hover:bg-neutral-900 transition-colors"
            >
              Manage Relays →
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
