// src/lib/pages/ArticlePage.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';
  import { ndk } from '$lib/ndk.svelte';
  import { fetchArticleByNaddr } from '$lib/utils/fetchArticle';
  import ArticleHeader from '$lib/components/ArticleHeader.svelte';
  import ArticleContent from '$lib/components/ArticleContent.svelte';
  import CommentSection from '$lib/components/CommentSection.svelte';
  import type { NDKArticle } from '@nostr-dev-kit/ndk';
  import { NDKKind, NDKList } from '@nostr-dev-kit/ndk';

  let article = $state<NDKArticle | null>(null);
  let isLoading = $state(true);
  let error = $state<string | null>(null);
  let isBookmarked = $state(false);
  let showShareMenu = $state(false);
  let copied = $state(false);
  let userError = $state<string | null>(null);

  const naddr = $derived($page.params.naddr);
  const currentUser = ndk.$currentUser;

  async function loadArticle() {
    if (!naddr) {
      error = 'No article identifier provided';
      isLoading = false;
      return;
    }

    isLoading = true;
    error = null;

    try {
      article = await fetchArticleByNaddr(ndk, naddr);
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to load article';
      console.error('Failed to load article:', err);
    } finally {
      isLoading = false;
    }
  }

  async function checkBookmark() {
    if (!currentUser || !article) return;

    try {
      const lists = await ndk.fetchEvents({
        kinds: [NDKKind.BookmarkSet],
        authors: [currentUser.pubkey],
        '#d': ['bookmarks']
      });

      const bookmarkList = Array.from(lists)[0];
      if (bookmarkList) {
        const bookmarkedItems = bookmarkList.tags
          .filter(tag => tag[0] === 'a')
          .map(tag => tag[1]);

        const articlePointer = article.tagId();
        isBookmarked = bookmarkedItems.includes(articlePointer);
      }
    } catch (err) {
      console.error('Failed to check bookmark status:', err);
    }
  }

  async function handleBookmark() {
    if (!currentUser || !article) return;

    try {
      const lists = await ndk.fetchEvents({
        kinds: [NDKKind.BookmarkSet],
        authors: [currentUser.pubkey],
        '#d': ['bookmarks']
      });

      let bookmarkList = Array.from(lists)[0] as NDKList | undefined;

      if (!bookmarkList) {
        bookmarkList = new NDKList(ndk);
        bookmarkList.kind = NDKKind.BookmarkSet;
        bookmarkList.tags = [
          ['d', 'bookmarks'],
          ['title', 'Bookmarks']
        ];
      }

      const articlePointer = article.tagId();

      if (isBookmarked) {
        bookmarkList.tags = bookmarkList.tags.filter(
          tag => !(tag[0] === 'a' && tag[1] === articlePointer)
        );
      } else {
        bookmarkList.addItem(['a', articlePointer, '', article.author.pubkey]);
      }

      await bookmarkList.publish();
      isBookmarked = !isBookmarked;
    } catch (err) {
      console.error('Bookmark error:', err);
    }
  }

  function handleCopyIdentifier() {
    if (!article) return;

    const identifier = article.encode();
    navigator.clipboard.writeText(identifier);
    copied = true;
    setTimeout(() => copied = false, 2000);
  }

  function handleShare(platform: string) {
    if (!article) return;

    const title = encodeURIComponent(article.title || 'Check out this article');
    const url = encodeURIComponent(window.location.href);
    const text = encodeURIComponent(`${article.title} by ${article.author.profile?.name || 'Anonymous'}`);

    const shareUrls: Record<string, string> = {
      twitter: `https://twitter.com/intent/tweet?text=${text}&url=${url}`,
      facebook: `https://www.facebook.com/sharer/sharer.php?u=${url}`,
      linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${url}&title=${title}`,
    };

    if (shareUrls[platform]) {
      window.open(shareUrls[platform], '_blank', 'width=600,height=400');
    }

    showShareMenu = false;
  }

  function goBack() {
    window.history.back();
  }

  $effect(() => {
    if (naddr) {
      loadArticle().then(() => {
        if (article) {
          checkBookmark();
        }
      });
    }
  });
</script>

{#if isLoading}
  <div class="flex flex-col items-center justify-center min-h-screen bg-white dark:bg-black">
    <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-neutral-900 dark:border-white"></div>
    <p class="mt-4 text-neutral-600 dark:text-neutral-400">Loading article...</p>
  </div>
{:else if error || !article}
  <div class="flex flex-col items-center justify-center min-h-screen px-4 bg-white dark:bg-black">
    <h1 class="text-2xl font-bold text-neutral-900 dark:text-white mb-2">Article Not Found</h1>
    <p class="text-neutral-600 dark:text-neutral-400 mb-4">{error || 'The article could not be loaded.'}</p>
    <button
      type="button"
      onclick={() => goto('/')}
      class="px-4 py-2 bg-neutral-900 dark:bg-white text-white dark:text-black rounded-full hover:bg-neutral-800 dark:hover:bg-neutral-100 transition-colors text-sm font-medium"
    >
      Go Home
    </button>
  </div>
{:else}
  <div class="min-h-screen bg-white dark:bg-black">
    <header class="fixed top-0 left-0 right-0 z-50 bg-white/95 dark:bg-black/95 backdrop-blur-sm">
      <div class="max-w-screen-lg mx-auto px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
          <button
            type="button"
            onclick={goBack}
            class="p-2 hover:bg-neutral-100 dark:hover:bg-neutral-900 rounded-full transition-colors"
            aria-label="Go back"
          >
            <svg class="w-5 h-5 text-neutral-700 dark:text-neutral-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
            </svg>
          </button>

          <div class="flex items-center gap-2">
            <button
              type="button"
              onclick={handleBookmark}
              disabled={!currentUser}
              class={`p-2 rounded-full transition-colors ${
                isBookmarked
                  ? 'text-yellow-600 dark:text-yellow-400 hover:bg-yellow-50 dark:hover:bg-yellow-900/20'
                  : 'hover:bg-neutral-100 dark:hover:bg-neutral-900 text-neutral-700 dark:text-neutral-300'
              } ${!currentUser ? 'opacity-50 cursor-not-allowed' : ''}`}
              title={currentUser ? (isBookmarked ? 'Remove bookmark' : 'Add bookmark') : 'Login to bookmark'}
            >
              <svg class={`w-5 h-5 ${isBookmarked ? 'fill-current' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z" />
              </svg>
            </button>

            <div class="relative">
              <button
                type="button"
                onclick={() => showShareMenu = !showShareMenu}
                class="p-2 hover:bg-neutral-100 dark:hover:bg-neutral-900 rounded-full transition-colors"
              >
                <svg class="w-5 h-5 text-neutral-700 dark:text-neutral-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
                </svg>
              </button>

              {#if showShareMenu}
                <div class="absolute right-0 mt-2 w-48 bg-white dark:bg-neutral-900 rounded-lg shadow-lg border border-neutral-200 dark:border-neutral-800">
                  <button
                    type="button"
                    onclick={() => handleShare('twitter')}
                    class="w-full px-4 py-2 text-left hover:bg-neutral-50 dark:hover:bg-neutral-800 flex items-center gap-3"
                  >
                    Share on X
                  </button>
                  <button
                    type="button"
                    onclick={() => handleShare('facebook')}
                    class="w-full px-4 py-2 text-left hover:bg-neutral-50 dark:hover:bg-neutral-800 flex items-center gap-3"
                  >
                    Share on Facebook
                  </button>
                  <button
                    type="button"
                    onclick={() => handleShare('linkedin')}
                    class="w-full px-4 py-2 text-left hover:bg-neutral-50 dark:hover:bg-neutral-800 flex items-center gap-3"
                  >
                    Share on LinkedIn
                  </button>
                </div>
              {/if}
            </div>

            <button
              type="button"
              onclick={handleCopyIdentifier}
              class="p-2 hover:bg-neutral-100 dark:hover:bg-neutral-900 rounded-full transition-colors"
            >
              {#if copied}
                <svg class="w-5 h-5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                </svg>
              {:else}
                <svg class="w-5 h-5 text-neutral-700 dark:text-neutral-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                </svg>
              {/if}
            </button>
          </div>
        </div>
      </div>
    </header>

    <main class="pt-24 pb-32">
      <article class="max-w-screen-md mx-auto px-6 lg:px-8">
        {#if userError}
          <div class="mb-6 p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg">
            <div class="flex items-start justify-between">
              <p class="text-red-600 dark:text-red-400">{userError}</p>
              <button
                type="button"
                onclick={() => userError = null}
                class="text-red-600 dark:text-red-400 hover:text-red-800 dark:hover:text-red-300"
              >
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>
        {/if}

        <ArticleHeader {article} />
        <ArticleContent content={article.content} emojiTags={article.tags} />
      </article>

      <div class="max-w-screen-md mx-auto px-6 lg:px-8 mt-16">
        <CommentSection {article} onError={(err) => userError = err} />
      </div>
    </main>
  </div>
{/if}

// src/pages/ArticlePage.tsx
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Share2, Bookmark, MoreHorizontal, Copy, Twitter, Facebook, Linkedin, CheckCircle } from 'lucide-react';
import { useArticle } from '@/features/articles/hooks/useArticle';
import { ArticleHeader } from '@/features/articles/components/ArticleHeader';
import { ArticleContent } from '@/features/articles/components/ArticleContent';
import { CommentSection } from '@/features/articles/components/CommentSection';
import { ErrorAlert } from '@/components/ui/ErrorAlert';
import { useErrorHandler } from '@/hooks/useErrorHandler';
import { useState, useRef, useEffect } from 'react';
import { useNDKCurrentUser, useNDK } from '@nostr-dev-kit/ndk-hooks';
import { NDKList, NDKKind } from '@nostr-dev-kit/ndk';

export function ArticlePage() {
  const { naddr } = useParams<{ naddr: string }>();
  const navigate = useNavigate();
  const { article, isLoading, error: fetchError } = useArticle(naddr);
  const { error: userError, handleError, clearError } = useErrorHandler();
  const currentUser = useNDKCurrentUser();
  const { ndk } = useNDK();

  const [isBookmarked, setIsBookmarked] = useState(false);
  const [showDropdown, setShowDropdown] = useState(false);
  const [showShareMenu, setShowShareMenu] = useState(false);
  const [copied, setCopied] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const shareMenuRef = useRef<HTMLDivElement>(null);

  // Check if article is bookmarked
  useEffect(() => {
    if (!currentUser || !article) return;

    const checkBookmark = async () => {
      try {
        // Fetch user's bookmark list (NIP-51 kind:30001 with "d" tag "bookmarks")
        const lists = await ndk.fetchEvents({
          kinds: [NDKKind.BookmarkSet],
          authors: [currentUser.pubkey],
          '#d': ['bookmarks']
        });

        const bookmarkList = Array.from(lists)[0];
        if (bookmarkList) {
          const bookmarkedItems = bookmarkList.tags
            .filter(tag => tag[0] === 'a')
            .map(tag => tag[1]);

          const articlePointer = article.tagId();
          setIsBookmarked(bookmarkedItems.includes(articlePointer));
        }
      } catch (error) {
        console.error('Failed to check bookmark status:', error);
      }
    };

    checkBookmark();
  }, [currentUser, article, ndk]);

  // Handle clicking outside dropdowns
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setShowDropdown(false);
      }
      if (shareMenuRef.current && !shareMenuRef.current.contains(event.target as Node)) {
        setShowShareMenu(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const handleBookmark = async () => {
    if (!currentUser || !article) return;

    try {
      // Fetch or create bookmark list
      const lists = await ndk.fetchEvents({
        kinds: [NDKKind.BookmarkSet],
        authors: [currentUser.pubkey],
        '#d': ['bookmarks']
      });

      let bookmarkList = Array.from(lists)[0] as NDKList | undefined;

      if (!bookmarkList) {
        // Create new bookmark list
        bookmarkList = new NDKList(ndk);
        bookmarkList.kind = NDKKind.BookmarkSet;
        bookmarkList.tags = [
          ['d', 'bookmarks'],
          ['title', 'Bookmarks']
        ];
      }

      const articlePointer = article.tagId();

      if (isBookmarked) {
        // Remove bookmark
        bookmarkList.tags = bookmarkList.tags.filter(
          tag => !(tag[0] === 'a' && tag[1] === articlePointer)
        );
      } else {
        // Add bookmark
        bookmarkList.addItem(['a', articlePointer, article.relay?.url || '', article.author.pubkey]);
      }

      await bookmarkList.publish();
      setIsBookmarked(!isBookmarked);
    } catch (error) {
      handleError('Failed to update bookmarks');
      console.error('Bookmark error:', error);
    }
  };

  const handleCopyIdentifier = () => {
    if (!article) return;

    const identifier = article.encode();
    navigator.clipboard.writeText(identifier);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    setShowDropdown(false);
  };

  const handleShare = (platform: string) => {
    if (!article) return;

    const title = encodeURIComponent(article.title || 'Check out this article');
    const url = encodeURIComponent(window.location.href);
    const text = encodeURIComponent(`${article.title} by ${article.author.profile?.name || 'Anonymous'}`);

    const shareUrls: Record<string, string> = {
      twitter: `https://twitter.com/intent/tweet?text=${text}&url=${url}`,
      facebook: `https://www.facebook.com/sharer/sharer.php?u=${url}`,
      linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${url}&title=${title}`,
    };

    if (shareUrls[platform]) {
      window.open(shareUrls[platform], '_blank', 'width=600,height=400');
    }

    setShowShareMenu(false);
  };

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen bg-white dark:bg-black">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-neutral-900 dark:border-white"></div>
        <p className="mt-4 text-neutral-600 dark:text-neutral-400">Loading article...</p>
      </div>
    );
  }

  if (fetchError || !article) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen px-4 bg-white dark:bg-black">
        <h1 className="text-2xl font-bold text-neutral-900 dark:text-white mb-2">Article Not Found</h1>
        <p className="text-neutral-600 dark:text-neutral-400 mb-4">{fetchError || 'The article could not be loaded.'}</p>
        <button
          onClick={() => navigate('/')}
          className="px-4 py-2 bg-neutral-900 dark:bg-white text-white dark:text-black rounded-full hover:bg-neutral-800 dark:hover:bg-neutral-100 transition-colors text-sm font-medium"
        >
          Go Home
        </button>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white dark:bg-black">
      {/* Minimal Header */}
      <header className="fixed top-0 left-0 right-0 z-50 bg-white/95 dark:bg-black/95 backdrop-blur-sm">
        <div className="max-w-screen-lg mx-auto px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <button
              onClick={() => navigate(-1)}
              className="p-2 hover:bg-neutral-100 dark:hover:bg-neutral-900 rounded-full transition-colors"
              aria-label="Go back"
            >
              <ArrowLeft className="w-5 h-5 text-neutral-700 dark:text-neutral-300" />
            </button>

            <div className="flex items-center gap-2">
              {/* Bookmark Button */}
              <button
                onClick={handleBookmark}
                disabled={!currentUser}
                className={`p-2 rounded-full transition-colors ${
                  isBookmarked
                    ? 'text-yellow-600 dark:text-yellow-400 hover:bg-yellow-50 dark:hover:bg-yellow-900/20'
                    : 'hover:bg-neutral-100 dark:hover:bg-neutral-900 text-neutral-700 dark:text-neutral-300'
                } ${!currentUser ? 'opacity-50 cursor-not-allowed' : ''}`}
                title={currentUser ? (isBookmarked ? 'Remove bookmark' : 'Add bookmark') : 'Login to bookmark'}
              >
                <Bookmark className={`w-5 h-5 ${isBookmarked ? 'fill-current' : ''}`} />
              </button>

              {/* Share Button */}
              <div className="relative" ref={shareMenuRef}>
                <button
                  onClick={() => setShowShareMenu(!showShareMenu)}
                  className="p-2 hover:bg-neutral-100 dark:hover:bg-neutral-900 rounded-full transition-colors"
                >
                  <Share2 className="w-5 h-5 text-neutral-700 dark:text-neutral-300" />
                </button>

                {showShareMenu && (
                  <div className="absolute right-0 mt-2 w-48 bg-white dark:bg-neutral-900 rounded-lg shadow-lg border border-neutral-200 dark:border-neutral-800">
                    <button
                      onClick={() => handleShare('twitter')}
                      className="w-full px-4 py-2 text-left hover:bg-neutral-50 dark:hover:bg-neutral-800 flex items-center gap-3"
                    >
                      <Twitter className="w-4 h-4" />
                      Share on X
                    </button>
                    <button
                      onClick={() => handleShare('facebook')}
                      className="w-full px-4 py-2 text-left hover:bg-neutral-50 dark:hover:bg-neutral-800 flex items-center gap-3"
                    >
                      <Facebook className="w-4 h-4" />
                      Share on Facebook
                    </button>
                    <button
                      onClick={() => handleShare('linkedin')}
                      className="w-full px-4 py-2 text-left hover:bg-neutral-50 dark:hover:bg-neutral-800 flex items-center gap-3"
                    >
                      <Linkedin className="w-4 h-4" />
                      Share on LinkedIn
                    </button>
                  </div>
                )}
              </div>

              {/* More Options Button */}
              <div className="relative" ref={dropdownRef}>
                <button
                  onClick={() => setShowDropdown(!showDropdown)}
                  className="p-2 hover:bg-neutral-100 dark:hover:bg-neutral-900 rounded-full transition-colors"
                >
                  <MoreHorizontal className="w-5 h-5 text-neutral-700 dark:text-neutral-300" />
                </button>

                {showDropdown && (
                  <div className="absolute right-0 mt-2 w-56 bg-white dark:bg-neutral-900 rounded-lg shadow-lg border border-neutral-200 dark:border-neutral-800">
                    <button
                      onClick={handleCopyIdentifier}
                      className="w-full px-4 py-2 text-left hover:bg-neutral-50 dark:hover:bg-neutral-800 flex items-center gap-3"
                    >
                      {copied ? (
                        <>
                          <CheckCircle className="w-4 h-4 text-green-600" />
                          <span className="text-green-600">Copied!</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-4 h-4" />
                          Copy Article Identifier
                        </>
                      )}
                    </button>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="pt-24 pb-32">
        <article className="max-w-screen-md mx-auto px-6 lg:px-8">
          {userError && (
            <ErrorAlert message={userError} onDismiss={clearError} />
          )}

          <ArticleHeader article={article} />
          <ArticleContent content={article.content} emojiTags={article.tags} />
        </article>

        {/* Comments Section */}
        <div className="max-w-screen-md mx-auto px-6 lg:px-8 mt-16">
          <CommentSection article={article} onError={handleError} />
        </div>
      </main>
    </div>
  );
}
