// src/lib/pages/FollowPacksPage.svelte
<script lang="ts">
  import { ndk } from '$lib/ndk.svelte';
  import { goto } from '$app/navigation';
  import { followPacksStore } from '$lib/stores/followPacks.svelte';
  import { mockFollowPacks } from '$lib/data/mockFollowPacks';
  import { NDKKind, type NDKEvent } from '@nostr-dev-kit/ndk';
  import { Avatar } from '@nostr-dev-kit/svelte';

  let searchQuery = $state('');

  // Subscribe to follow packs from relays
  const subscription = ndk.$subscribe(
    () => ({
      filters: [{ kinds: [39089, 39092] }],
      bufferMs: 100,
    })
  );

  const packEvents = $derived(subscription.events);
  const eosed = $derived(subscription.eosed);

  // Convert events to pack objects
  interface Pack {
    id: string;
    title: string;
    description?: string;
    image?: string;
    pubkeys: string[];
    encode: () => string;
    kind: number;
    pubkey: string;
    created_at: number;
  }

  let packs = $derived.by(() => {
    const relayPacks: Pack[] = packEvents.map(event => ({
      id: event.id || '',
      title: event.tagValue('title') || 'Untitled Pack',
      description: event.tagValue('description'),
      image: event.tagValue('image'),
      pubkeys: event.tags.filter(t => t[0] === 'p').map(t => t[1]),
      encode: () => event.encode(),
      kind: event.kind || 39089,
      pubkey: event.pubkey,
      created_at: event.created_at || 0,
    }));

    // Use relay packs if available, otherwise mock data
    return relayPacks.length > 0 ? relayPacks : mockFollowPacks;
  });

  let filteredPacks = $derived.by(() => {
    if (!searchQuery) return packs;
    const search = searchQuery.toLowerCase();
    return packs.filter(pack =>
      pack.title.toLowerCase().includes(search) ||
      (pack.description && pack.description.toLowerCase().includes(search))
    );
  });

  let subscribedPacks = $derived.by(() => {
    return packs.filter(pack => followPacksStore.isSubscribed(pack.id));
  });

  function handlePackClick(pack: Pack) {
    goto(`/packs/${pack.encode()}`);
  }

  function handleSubscribe(e: MouseEvent, pack: Pack) {
    e.preventDefault();
    e.stopPropagation();

    if (followPacksStore.isSubscribed(pack.id)) {
      followPacksStore.unsubscribeFromPack(pack.id);
    } else {
      followPacksStore.subscribeToPack(pack.id);
    }
  }
</script>

<div class="max-w-6xl mx-auto px-4 py-8">
  <!-- Header -->
  <div class="mb-8">
    <h1 class="text-3xl font-bold text-white mb-2 flex items-center gap-3">
      <svg class="w-8 h-8 text-orange-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
      </svg>
      Follow Packs
    </h1>
    <p class="text-neutral-400">
      Discover curated lists of accounts to follow
    </p>
  </div>

  <!-- Search -->
  <div class="mb-6">
    <div class="relative">
      <svg class="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-neutral-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
      </svg>
      <input
        type="search"
        placeholder="Search follow packs..."
        bind:value={searchQuery}
        class="w-full pl-10 pr-4 py-3 bg-neutral-900 border border-neutral-800 rounded-lg text-white placeholder:text-neutral-500 focus:outline-none focus:border-orange-500"
      />
    </div>
  </div>

  <!-- Your Subscribed Packs -->
  {#if subscribedPacks.length > 0}
    <div class="mb-8">
      <h2 class="text-xl font-semibold text-white mb-4">Your Packs</h2>
      <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {#each subscribedPacks as pack (pack.id)}
          <div
            role="button"
            tabindex="0"
            onclick={() => handlePackClick(pack)}
            onkeydown={(e) => e.key === 'Enter' && handlePackClick(pack)}
            class="block bg-neutral-900 border border-neutral-800 rounded-xl overflow-hidden hover:border-neutral-700 transition-colors group cursor-pointer"
          >
            {#if pack.image}
              <div class="h-32 w-full">
                <img
                  src={pack.image}
                  alt={pack.title}
                  class="w-full h-full object-cover"
                />
              </div>
            {/if}

            <div class="p-5">
              <div class="mb-4">
                <h3 class="font-semibold text-white group-hover:text-orange-500 transition-colors">
                  {pack.title}
                </h3>
                <p class="text-sm text-neutral-500 mt-1">
                  {pack.pubkeys.length} members
                </p>
              </div>

              {#if pack.description}
                <p class="text-sm text-neutral-400 mb-4 line-clamp-2">
                  {pack.description}
                </p>
              {/if}

              <div class="flex items-center justify-between">
                <div class="flex -space-x-2">
                  {#each pack.pubkeys.slice(0, 4) as pubkey, index (pubkey)}
                    <button
                      type="button"
                      onclick={(e) => { e.stopPropagation(); goto(`/p/${pubkey}`); }}
                      class="relative cursor-pointer"
                      style="z-index: {4 - index}"
                    >
                      <Avatar {ndk} {pubkey} class="w-8 h-8 rounded-full ring-2 ring-neutral-900 hover:opacity-80 transition-opacity" />
                    </button>
                  {/each}
                  {#if pack.pubkeys.length > 4}
                    <div class="w-8 h-8 rounded-full bg-neutral-800 ring-2 ring-neutral-900 flex items-center justify-center">
                      <span class="text-xs text-neutral-400">
                        +{pack.pubkeys.length - 4}
                      </span>
                    </div>
                  {/if}
                </div>

                <button
                  onclick={(e) => handleSubscribe(e, pack)}
                  class="px-3 py-1.5 text-sm font-medium border rounded-lg transition-colors bg-neutral-800 border-neutral-700 text-neutral-300 hover:bg-neutral-700"
                >
                  Following
                </button>
              </div>
            </div>
          </div>
        {/each}
      </div>
    </div>
  {/if}

  <!-- All Packs Grid -->
  <div>
    <h2 class="text-xl font-semibold text-white mb-4">
      {subscribedPacks.length > 0 ? 'Discover More' : 'Popular Packs'}
    </h2>
    {#if filteredPacks.length > 0}
      <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {#each filteredPacks as pack (pack.id)}
          <div
            role="button"
            tabindex="0"
            onclick={() => handlePackClick(pack)}
            onkeydown={(e) => e.key === 'Enter' && handlePackClick(pack)}
            class="block bg-neutral-900 border border-neutral-800 rounded-xl overflow-hidden hover:border-neutral-700 transition-colors group cursor-pointer"
          >
            {#if pack.image}
              <div class="h-32 w-full">
                <img
                  src={pack.image}
                  alt={pack.title}
                  class="w-full h-full object-cover"
                />
              </div>
            {/if}

            <div class="p-5">
              <div class="mb-4">
                <h3 class="font-semibold text-white group-hover:text-orange-500 transition-colors">
                  {pack.title}
                </h3>
                <p class="text-sm text-neutral-500 mt-1">
                  {pack.pubkeys.length} members
                </p>
              </div>

              {#if pack.description}
                <p class="text-sm text-neutral-400 mb-4 line-clamp-2">
                  {pack.description}
                </p>
              {/if}

              <div class="flex items-center justify-between">
                <div class="flex -space-x-2">
                  {#each pack.pubkeys.slice(0, 4) as pubkey, index (pubkey)}
                    <button
                      type="button"
                      onclick={(e) => { e.stopPropagation(); goto(`/p/${pubkey}`); }}
                      class="relative cursor-pointer"
                      style="z-index: {4 - index}"
                    >
                      <Avatar {ndk} {pubkey} class="w-8 h-8 rounded-full ring-2 ring-neutral-900 hover:opacity-80 transition-opacity" />
                    </button>
                  {/each}
                  {#if pack.pubkeys.length > 4}
                    <div class="w-8 h-8 rounded-full bg-neutral-800 ring-2 ring-neutral-900 flex items-center justify-center">
                      <span class="text-xs text-neutral-400">
                        +{pack.pubkeys.length - 4}
                      </span>
                    </div>
                  {/if}
                </div>

                <button
                  onclick={(e) => handleSubscribe(e, pack)}
                  class="px-3 py-1.5 text-sm font-medium border rounded-lg transition-colors {followPacksStore.isSubscribed(pack.id) ? 'bg-neutral-800 border-neutral-700 text-neutral-300 hover:bg-neutral-700' : 'bg-orange-500 border-orange-500 text-white hover:bg-orange-500/90'}"
                >
                  {followPacksStore.isSubscribed(pack.id) ? 'Following' : 'Follow'}
                </button>
              </div>
            </div>
          </div>
        {/each}
      </div>
    {:else}
      <div class="text-center py-12">
        <svg class="w-16 h-16 text-neutral-600 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
        </svg>
        <p class="text-neutral-400">
          No follow packs found
        </p>
      </div>
    {/if}
  </div>
</div>

// src/pages/FollowPacksPage.tsx
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Package, Search } from 'lucide-react';
import { NDKFollowPack } from '@nostr-dev-kit/ndk-hooks';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { useFollowPacks, useSubscribedFollowPacks } from '@/features/followPacks/hooks/useFollowPacks';
import { useFollowPacksStore } from '@/stores/followPacksStore';
import { ProfileAvatar } from '@/features/followPacks/components/ProfileAvatar';
import { mockFollowPacks } from '@/features/followPacks/mockData';

export function FollowPacksPage() {
  const [searchQuery, setSearchQuery] = useState('');
  const { packs } = useFollowPacks();
  const subscribedPacks = useSubscribedFollowPacks();

  // Use mock data if no packs from relays
  const displayPacks = packs.length > 0 ? packs : mockFollowPacks as any[];

  // Filter packs based on search
  const filteredPacks = displayPacks.filter(pack => {
    if (!searchQuery) return true;
    const search = searchQuery.toLowerCase();
    return pack.title.toLowerCase().includes(search) ||
           (pack.description && pack.description.toLowerCase().includes(search));
  });

  return (
    <div className="max-w-6xl mx-auto px-4 py-8">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-white mb-2 flex items-center gap-3">
          <Package className="w-8 h-8 text-orange-500" />
          Follow Packs
        </h1>
        <p className="text-neutral-400">
          Discover curated lists of accounts to follow
        </p>
      </div>

      {/* Search */}
      <div className="mb-6">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-neutral-500" />
          <Input
            type="search"
            placeholder="Search follow packs..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-10 bg-neutral-900 border-neutral-800 text-white placeholder:text-neutral-500"
          />
        </div>
      </div>

      {/* Your Subscribed Packs */}
      {subscribedPacks.length > 0 && (
        <div className="mb-8">
          <h2 className="text-xl font-semibold text-white mb-4">Your Packs</h2>
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {subscribedPacks.map(pack => (
              <PackCard key={pack.id} pack={pack} />
            ))}
          </div>
        </div>
      )}

      {/* All Packs Grid */}
      <div>
        <h2 className="text-xl font-semibold text-white mb-4">
          {subscribedPacks.length > 0 ? 'Discover More' : 'Popular Packs'}
        </h2>
        {filteredPacks.length > 0 ? (
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {filteredPacks.map(pack => (
              <PackCard key={pack.id} pack={pack} />
            ))}
          </div>
        ) : (
          <div className="text-center py-12">
            <Package className="w-16 h-16 text-neutral-600 mx-auto mb-4" />
            <p className="text-neutral-400">
              No follow packs found
            </p>
          </div>
        )}
      </div>
    </div>
  );
}

function PackCard({ pack }: { pack: NDKFollowPack }) {
  const { isSubscribed, subscribeToPack, unsubscribeFromPack } = useFollowPacksStore();
  const subscribed = isSubscribed(pack.id);
  const previewPubkeys = pack.pubkeys.slice(0, 4);

  const handleSubscribe = (e: React.MouseEvent) => {
    e.preventDefault();
    if (subscribed) {
      unsubscribeFromPack(pack.id);
    } else {
      subscribeToPack(pack.id);
    }
  };

  return (
    <Link
      to={`/packs/${pack.encode()}`}
      className="block bg-neutral-900 border border-neutral-800 rounded-xl overflow-hidden hover:border-neutral-700 transition-colors group"
    >
      {/* Image */}
      {pack.image && (
        <div className="h-32 w-full">
          <img
            src={pack.image}
            alt={pack.title}
            className="w-full h-full object-cover"
          />
        </div>
      )}

      {/* Content padding wrapper */}
      <div className="p-5">
        {/* Header */}
        <div className="mb-4">
          <h3 className="font-semibold text-white group-hover:text-orange-500 transition-colors">
            {pack.title}
          </h3>
          <p className="text-sm text-neutral-500 mt-1">
            {pack.pubkeys.length} members
          </p>
        </div>

        {/* Description */}
        {pack.description && (
          <p className="text-sm text-neutral-400 mb-4 line-clamp-2">
            {pack.description}
          </p>
        )}

        {/* Member Avatars */}
        <div className="flex items-center justify-between">
          <div className="flex -space-x-2">
            {previewPubkeys.map((pubkey: string, index: number) => (
              <div
                key={pubkey}
                className="relative"
                style={{ zIndex: 4 - index }}
              >
                <ProfileAvatar
                  pubkey={pubkey}
                  size="sm"
                  className="ring-2 ring-neutral-900"
                />
              </div>
            ))}
            {pack.pubkeys.length > 4 && (
              <div className="w-8 h-8 rounded-full bg-neutral-800 ring-2 ring-neutral-900 flex items-center justify-center">
                <span className="text-xs text-neutral-400">
                  +{pack.pubkeys.length - 4}
                </span>
              </div>
            )}
          </div>

          <Button
            onClick={handleSubscribe}
            size="sm"
            variant={subscribed ? 'outline' : 'primary'}
            className="ml-2"
          >
            {subscribed ? 'Following' : 'Follow'}
          </Button>
        </div>
      </div>
    </Link>
  );
}
