// src/lib/components/settings/RelaySettings.svelte
<script lang="ts">
  import { settings } from '$lib/stores/settings.svelte';
  import RelayDetailsComponent from './RelayDetailsComponent.svelte';

  let isAdding = $state(false);
  let newRelay = $state({ url: '', read: true, write: true });
  let testingRelay = $state<string | null>(null);
  let connectionStatus = $state<Record<string, 'connected' | 'disconnected' | 'testing'>>({});

  function handleAddRelay() {
    if (newRelay.url && !settings.relays.some(r => r.url === newRelay.url)) {
      settings.addRelay({
        ...newRelay,
        enabled: true,
        url: newRelay.url.startsWith('wss://') ? newRelay.url : `wss://${newRelay.url}`,
      });
      newRelay = { url: '', read: true, write: true };
      isAdding = false;
    }
  }

  async function testRelayConnection(url: string) {
    testingRelay = url;
    connectionStatus = { ...connectionStatus, [url]: 'testing' };

    // Mock connection test
    setTimeout(() => {
      const isConnected = Math.random() > 0.3; // 70% success rate for demo
      connectionStatus = {
        ...connectionStatus,
        [url]: isConnected ? 'connected' : 'disconnected'
      };
      testingRelay = null;
    }, 1500);
  }

  function getRelayStatus(url: string) {
    if (testingRelay === url) return 'testing';
    return connectionStatus[url] || 'disconnected';
  }

  let relays = $derived(settings.relays);
</script>

<div class="space-y-6">
  <div>
    <h2 class="text-xl font-semibold text-neutral-900 dark:text-neutral-100 mb-2">
      Relay Configuration
    </h2>
    <p class="text-sm text-neutral-600 dark:text-neutral-400">
      Configure which Nostr relays your app connects to for reading and publishing events.
    </p>
  </div>

  <!-- Stats -->
  <div class="grid grid-cols-3 gap-2 md:gap-4">
    <div class="bg-neutral-50 dark:bg-black rounded-lg p-3 md:p-4">
      <div class="flex items-center gap-1 md:gap-2 text-green-600 dark:text-green-400 mb-1">
        <svg class="w-3 h-3 md:w-4 md:h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.111 16.404a5.5 5.5 0 017.778 0M12 20h.01m-7.08-7.071c3.904-3.905 10.236-3.905 14.141 0M1.394 9.393c5.857-5.857 15.355-5.857 21.213 0" />
        </svg>
        <span class="text-xs md:text-sm font-medium">Active</span>
      </div>
      <div class="text-xl md:text-2xl font-bold text-neutral-900 dark:text-neutral-100">
        {relays.filter(r => r.enabled).length}
      </div>
    </div>
    <div class="bg-neutral-50 dark:bg-black rounded-lg p-3 md:p-4">
      <div class="flex items-center gap-1 md:gap-2 text-blue-600 dark:text-blue-400 mb-1">
        <svg class="w-3 h-3 md:w-4 md:h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
        </svg>
        <span class="text-xs md:text-sm font-medium">Read</span>
      </div>
      <div class="text-xl md:text-2xl font-bold text-neutral-900 dark:text-neutral-100">
        {relays.filter(r => r.enabled && r.read).length}
      </div>
    </div>
    <div class="bg-neutral-50 dark:bg-black rounded-lg p-3 md:p-4">
      <div class="flex items-center gap-1 md:gap-2 text-orange-600 dark:text-orange-500 mb-1">
        <svg class="w-3 h-3 md:w-4 md:h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
        </svg>
        <span class="text-xs md:text-sm font-medium">Write</span>
      </div>
      <div class="text-xl md:text-2xl font-bold text-neutral-900 dark:text-neutral-100">
        {relays.filter(r => r.enabled && r.write).length}
      </div>
    </div>
  </div>

  <!-- Relay List -->
  <div class="space-y-2">
    {#each relays as relay (relay.url)}
      {@const status = getRelayStatus(relay.url)}
      <div class="border rounded-lg p-4 transition-all {relay.enabled
        ? 'bg-white dark:bg-black border-neutral-200 dark:border-neutral-700'
        : 'bg-neutral-50 dark:bg-black border-neutral-200 dark:border-neutral-800 opacity-60'}">
        <div class="flex flex-col md:flex-row md:items-start md:justify-between gap-3">
          <div class="flex-1">
            <div class="flex items-start md:items-center gap-3">
              <button
                onclick={() => settings.toggleRelay(relay.url)}
                class="w-5 h-5 rounded-full border-2 flex items-center justify-center transition-all flex-shrink-0 mt-0.5 md:mt-0 {relay.enabled
                  ? 'bg-orange-600 border-orange-600'
                  : 'bg-white dark:bg-black border-neutral-300 dark:border-neutral-600'}"
              >
                {#if relay.enabled}
                  <svg class="w-3 h-3 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                  </svg>
                {/if}
              </button>
              <RelayDetailsComponent {relay} {status} {connectionStatus} />
            </div>
          </div>
          <div class="flex items-center gap-2 ml-8 md:ml-0">
            <button
              onclick={() => testRelayConnection(relay.url)}
              disabled={testingRelay === relay.url}
              class="p-1.5 md:p-2 hover:bg-neutral-100 dark:hover:bg-neutral-900 rounded-lg transition-colors disabled:opacity-50"
              title="Test connection"
            >
              <svg class="w-4 h-4 text-neutral-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
            </button>
            <button
              onclick={() => settings.removeRelay(relay.url)}
              class="p-1.5 md:p-2 hover:bg-red-50 dark:hover:bg-red-950/30 rounded-lg transition-colors group"
              title="Remove relay"
            >
              <svg class="w-4 h-4 text-neutral-500 group-hover:text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    {/each}

    <!-- Add New Relay -->
    {#if isAdding}
      <div class="border-2 border-dashed border-orange-300 dark:border-orange-700 rounded-lg p-4">
        <div class="space-y-3">
          <input
            type="text"
            bind:value={newRelay.url}
            placeholder="wss://relay.example.com"
            class="w-full px-3 py-2 bg-white dark:bg-black border border-neutral-300 dark:border-neutral-600 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
            autofocus
          />
          <div class="flex items-center gap-4">
            <label class="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                bind:checked={newRelay.read}
                class="w-4 h-4 text-orange-600 rounded focus:ring-orange-500"
              />
              <span class="text-sm text-neutral-600 dark:text-neutral-400">Read</span>
            </label>
            <label class="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                bind:checked={newRelay.write}
                class="w-4 h-4 text-orange-600 rounded focus:ring-orange-500"
              />
              <span class="text-sm text-neutral-600 dark:text-neutral-400">Write</span>
            </label>
          </div>
          <div class="flex gap-2">
            <button
              onclick={handleAddRelay}
              disabled={!newRelay.url}
              class="px-4 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              Add Relay
            </button>
            <button
              onclick={() => {
                isAdding = false;
                newRelay = { url: '', read: true, write: true };
              }}
              class="px-4 py-2 bg-neutral-200 dark:bg-black text-neutral-700 dark:text-neutral-300 rounded-lg hover:bg-neutral-300 dark:hover:bg-neutral-900 transition-colors"
            >
              Cancel
            </button>
          </div>
        </div>
      </div>
    {:else}
      <button
        onclick={() => isAdding = true}
        class="w-full border-2 border-dashed border-neutral-300 dark:border-neutral-700 rounded-lg p-4 hover:border-orange-500 dark:hover:border-orange-600 transition-colors group"
      >
        <div class="flex items-center justify-center gap-2 text-neutral-500 group-hover:text-orange-600 dark:group-hover:text-orange-500">
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
          </svg>
          <span class="font-medium">Add Relay</span>
        </div>
      </button>
    {/if}
  </div>

  <!-- Warning -->
  <div class="bg-yellow-50 dark:bg-yellow-950/30 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4">
    <div class="flex gap-3">
      <svg class="w-5 h-5 text-yellow-600 dark:text-yellow-400 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
      </svg>
      <div class="text-sm text-yellow-800 dark:text-yellow-300">
        <p class="font-medium mb-1">Important</p>
        <p>Changes to relay configuration will take effect after refreshing the app.</p>
      </div>
    </div>
  </div>
</div>

// src/features/settings/RelaySettings.tsx
import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Plus,
  Trash2,
  Check,
  Zap,
  BookOpen,
  Edit2,
  Globe,
  AlertCircle,
  Wifi
} from 'lucide-react';
import { useSettingsStore } from '@/stores/settingsStore';
import { cn } from '@/lib/utils';

export function RelaySettings() {
  const { relays, addRelay, removeRelay, updateRelay, toggleRelay } = useSettingsStore();
  const [isAdding, setIsAdding] = useState(false);
  const [newRelay, setNewRelay] = useState({ url: '', read: true, write: true });
  const [testingRelay, setTestingRelay] = useState<string | null>(null);
  const [connectionStatus, setConnectionStatus] = useState<Record<string, 'connected' | 'disconnected' | 'testing'>>({});

  const handleAddRelay = () => {
    if (newRelay.url && !relays.some(r => r.url === newRelay.url)) {
      addRelay({
        ...newRelay,
        enabled: true,
        url: newRelay.url.startsWith('wss://') ? newRelay.url : `wss://${newRelay.url}`,
      });
      setNewRelay({ url: '', read: true, write: true });
      setIsAdding(false);
    }
  };

  const testRelayConnection = async (url: string) => {
    setTestingRelay(url);
    setConnectionStatus(prev => ({ ...prev, [url]: 'testing' }));

    // Mock connection test
    setTimeout(() => {
      const isConnected = Math.random() > 0.3; // 70% success rate for demo
      setConnectionStatus(prev => ({
        ...prev,
        [url]: isConnected ? 'connected' : 'disconnected'
      }));
      setTestingRelay(null);
    }, 1500);
  };

  const getRelayStatus = (url: string) => {
    if (testingRelay === url) return 'testing';
    return connectionStatus[url] || 'disconnected';
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-2">
          Relay Configuration
        </h2>
        <p className="text-sm text-gray-600 dark:text-gray-400">
          Configure which Nostr relays your app connects to for reading and publishing events.
        </p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-3 gap-2 md:gap-4">
        <div className="bg-gray-50 dark:bg-black rounded-lg p-3 md:p-4">
          <div className="flex items-center gap-1 md:gap-2 text-green-600 dark:text-green-400 mb-1">
            <Wifi className="w-3 h-3 md:w-4 md:h-4" />
            <span className="text-xs md:text-sm font-medium">Active</span>
          </div>
          <div className="text-xl md:text-2xl font-bold text-gray-900 dark:text-gray-100">
            {relays.filter(r => r.enabled).length}
          </div>
        </div>
        <div className="bg-gray-50 dark:bg-black rounded-lg p-3 md:p-4">
          <div className="flex items-center gap-1 md:gap-2 text-blue-600 dark:text-blue-400 mb-1">
            <BookOpen className="w-3 h-3 md:w-4 md:h-4" />
            <span className="text-xs md:text-sm font-medium">Read</span>
          </div>
          <div className="text-xl md:text-2xl font-bold text-gray-900 dark:text-gray-100">
            {relays.filter(r => r.enabled && r.read).length}
          </div>
        </div>
        <div className="bg-gray-50 dark:bg-black rounded-lg p-3 md:p-4">
          <div className="flex items-center gap-1 md:gap-2 text-purple-600 dark:text-purple-400 mb-1">
            <Edit2 className="w-3 h-3 md:w-4 md:h-4" />
            <span className="text-xs md:text-sm font-medium">Write</span>
          </div>
          <div className="text-xl md:text-2xl font-bold text-gray-900 dark:text-gray-100">
            {relays.filter(r => r.enabled && r.write).length}
          </div>
        </div>
      </div>

      {/* Relay List */}
      <div className="space-y-2">
        <AnimatePresence>
          {relays.map((relay) => {
            const status = getRelayStatus(relay.url);
            return (
              <motion.div
                key={relay.url}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: 20 }}
                className={cn(
                  'border rounded-lg p-4 transition-all',
                  relay.enabled
                    ? 'bg-white dark:bg-black border-gray-200 dark:border-gray-700'
                    : 'bg-gray-50 dark:bg-black border-gray-200 dark:border-gray-800 opacity-60'
                )}
              >
                <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-3">
                  <div className="flex-1">
                    <div className="flex items-start md:items-center gap-3">
                      <button
                        onClick={() => toggleRelay(relay.url)}
                        className={cn(
                          'w-5 h-5 rounded-full border-2 flex items-center justify-center transition-all flex-shrink-0 mt-0.5 md:mt-0',
                          relay.enabled
                            ? 'bg-purple-600 border-purple-600'
                            : 'bg-white dark:bg-black border-gray-300 dark:border-gray-600'
                        )}
                      >
                        {relay.enabled && <Check className="w-3 h-3 text-white" />}
                      </button>
                      <div className="flex-1 min-w-0">
                        <div className="flex flex-wrap items-center gap-2">
                          <Globe className="w-4 h-4 text-gray-400 flex-shrink-0" />
                          <span className="font-mono text-xs md:text-sm text-gray-900 dark:text-gray-100 break-all">
                            {relay.url}
                          </span>
                          {status === 'connected' && (
                            <span className="text-xs bg-green-100 dark:bg-green-950 text-green-700 dark:text-green-400 px-2 py-0.5 rounded-full">
                              Connected
                            </span>
                          )}
                          {status === 'disconnected' && connectionStatus[relay.url] !== undefined && (
                            <span className="text-xs bg-red-100 dark:bg-red-950 text-red-700 dark:text-red-400 px-2 py-0.5 rounded-full">
                              Offline
                            </span>
                          )}
                          {status === 'testing' && (
                            <span className="text-xs bg-yellow-100 dark:bg-yellow-950 text-yellow-700 dark:text-yellow-400 px-2 py-0.5 rounded-full">
                              Testing...
                            </span>
                          )}
                        </div>
                        <div className="flex items-center gap-4 mt-2">
                          <label className="flex items-center gap-2 cursor-pointer">
                            <input
                              type="checkbox"
                              checked={relay.read}
                              onChange={(e) => updateRelay(relay.url, { read: e.target.checked })}
                              className="w-4 h-4 text-purple-600 rounded focus:ring-purple-500"
                            />
                            <span className="text-sm text-gray-600 dark:text-gray-400">
                              Read
                            </span>
                          </label>
                          <label className="flex items-center gap-2 cursor-pointer">
                            <input
                              type="checkbox"
                              checked={relay.write}
                              onChange={(e) => updateRelay(relay.url, { write: e.target.checked })}
                              className="w-4 h-4 text-purple-600 rounded focus:ring-purple-500"
                            />
                            <span className="text-sm text-gray-600 dark:text-gray-400">
                              Write
                            </span>
                          </label>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2 ml-8 md:ml-0">
                    <button
                      onClick={() => testRelayConnection(relay.url)}
                      disabled={testingRelay === relay.url}
                      className="p-1.5 md:p-2 hover:bg-gray-100 dark:hover:bg-neutral-900 rounded-lg transition-colors disabled:opacity-50"
                      title="Test connection"
                    >
                      <Zap className="w-4 h-4 text-gray-500" />
                    </button>
                    <button
                      onClick={() => removeRelay(relay.url)}
                      className="p-1.5 md:p-2 hover:bg-red-50 dark:hover:bg-red-950/30 rounded-lg transition-colors group"
                      title="Remove relay"
                    >
                      <Trash2 className="w-4 h-4 text-gray-500 group-hover:text-red-600" />
                    </button>
                  </div>
                </div>
              </motion.div>
            );
          })}
        </AnimatePresence>

        {/* Add New Relay */}
        <AnimatePresence>
          {isAdding ? (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              className="border-2 border-dashed border-purple-300 dark:border-purple-700 rounded-lg p-4"
            >
              <div className="space-y-3">
                <input
                  type="text"
                  value={newRelay.url}
                  onChange={(e) => setNewRelay({ ...newRelay, url: e.target.value })}
                  placeholder="wss://relay.example.com"
                  className="w-full px-3 py-2 bg-white dark:bg-black border border-gray-300 dark:border-gray-600 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
                  autoFocus
                />
                <div className="flex items-center gap-4">
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={newRelay.read}
                      onChange={(e) => setNewRelay({ ...newRelay, read: e.target.checked })}
                      className="w-4 h-4 text-purple-600 rounded focus:ring-purple-500"
                    />
                    <span className="text-sm text-gray-600 dark:text-gray-400">Read</span>
                  </label>
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={newRelay.write}
                      onChange={(e) => setNewRelay({ ...newRelay, write: e.target.checked })}
                      className="w-4 h-4 text-purple-600 rounded focus:ring-purple-500"
                    />
                    <span className="text-sm text-gray-600 dark:text-gray-400">Write</span>
                  </label>
                </div>
                <div className="flex gap-2">
                  <button
                    onClick={handleAddRelay}
                    disabled={!newRelay.url}
                    className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                  >
                    Add Relay
                  </button>
                  <button
                    onClick={() => {
                      setIsAdding(false);
                      setNewRelay({ url: '', read: true, write: true });
                    }}
                    className="px-4 py-2 bg-gray-200 dark:bg-black text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-300 dark:hover:bg-neutral-900 transition-colors"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            </motion.div>
          ) : (
            <motion.button
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              onClick={() => setIsAdding(true)}
              className="w-full border-2 border-dashed border-gray-300 dark:border-gray-700 rounded-lg p-4 hover:border-purple-400 dark:hover:border-purple-600 transition-colors group"
            >
              <div className="flex items-center justify-center gap-2 text-gray-500 group-hover:text-purple-600 dark:group-hover:text-purple-400">
                <Plus className="w-5 h-5" />
                <span className="font-medium">Add Relay</span>
              </div>
            </motion.button>
          )}
        </AnimatePresence>
      </div>

      {/* Warning */}
      <div className="bg-yellow-50 dark:bg-yellow-950/30 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4">
        <div className="flex gap-3">
          <AlertCircle className="w-5 h-5 text-yellow-600 dark:text-yellow-400 flex-shrink-0 mt-0.5" />
          <div className="text-sm text-yellow-800 dark:text-yellow-300">
            <p className="font-medium mb-1">Important</p>
            <p>Changes to relay configuration will take effect after refreshing the app.</p>
          </div>
        </div>
      </div>
    </div>
  );
}
