// src/lib/components/LoginButton.svelte
<script lang="ts">
  import { ndk, initializeSigner } from '$lib/ndk.svelte';
  import { NDKNip07Signer, NDKPrivateKeySigner } from '@nostr-dev-kit/ndk';

  interface Props {
    class?: string;
  }

  const { class: className = "px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-lg transition-colors font-semibold" }: Props = $props();

  let isLoggingIn = $state(false);
  let showLoginModal = $state(false);
  let loginMethod = $state<'nip07' | 'nsec' | null>(null);
  let nsecInput = $state('');
  let error = $state('');

  async function loginWithNip07() {
    if (!window.nostr) {
      error = 'No Nostr extension found. Please install Alby or nos2x.';
      return;
    }

    try {
      isLoggingIn = true;
      error = '';
      const signer = new NDKNip07Signer();
      ndk.signer = signer;
      const user = await signer.user();
      ndk.activeUser = user;
      showLoginModal = false;
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to login';
    } finally {
      isLoggingIn = false;
    }
  }

  async function loginWithNsec() {
    if (!nsecInput.trim()) {
      error = 'Please enter your nsec';
      return;
    }

    try {
      isLoggingIn = true;
      error = '';
      const signer = new NDKPrivateKeySigner(nsecInput.trim());
      ndk.signer = signer;
      const user = await signer.user();
      ndk.activeUser = user;

      localStorage.setItem('nostr_private_key', nsecInput.trim());

      showLoginModal = false;
      nsecInput = '';
    } catch (err) {
      error = err instanceof Error ? err.message : 'Invalid nsec';
    } finally {
      isLoggingIn = false;
    }
  }

  function openLoginModal() {
    showLoginModal = true;
    loginMethod = null;
    error = '';
  }

  function closeLoginModal() {
    showLoginModal = false;
    loginMethod = null;
    nsecInput = '';
    error = '';
  }
</script>

<button
  onclick={openLoginModal}
  class={className}
>
  <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1" />
  </svg>
  <span>Login</span>
</button>

{#if showLoginModal}
  <div class="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4" onclick={closeLoginModal}>
    <div class="bg-neutral-900 rounded-xl border border-neutral-800 max-w-md w-full p-6" onclick={(e) => e.stopPropagation()}>
      <div class="flex items-center justify-between mb-6">
        <h2 class="text-2xl font-bold text-white">Login to Voces</h2>
        <button onclick={closeLoginModal} class="text-neutral-400 hover:text-white">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      {#if !loginMethod}
        <div class="space-y-3">
          <button
            onclick={() => loginMethod = 'nip07'}
            class="w-full p-4 bg-neutral-800 hover:bg-neutral-700 rounded-lg transition-colors text-left"
          >
            <div class="font-semibold text-white mb-1">Browser Extension</div>
            <div class="text-sm text-neutral-400">Use Alby, nos2x, or similar</div>
          </button>

          <button
            onclick={() => loginMethod = 'nsec'}
            class="w-full p-4 bg-neutral-800 hover:bg-neutral-700 rounded-lg transition-colors text-left"
          >
            <div class="font-semibold text-white mb-1">Private Key (nsec)</div>
            <div class="text-sm text-neutral-400">Login with your private key</div>
          </button>
        </div>
      {:else if loginMethod === 'nip07'}
        <div class="space-y-4">
          <p class="text-neutral-300">
            Click the button below to connect with your Nostr extension.
          </p>

          {#if error}
            <div class="p-3 bg-red-500/10 border border-red-500/20 rounded-lg text-red-400 text-sm">
              {error}
            </div>
          {/if}

          <div class="flex gap-2">
            <button
              onclick={() => loginMethod = null}
              class="flex-1 px-4 py-2 bg-neutral-800 hover:bg-neutral-700 text-white rounded-lg transition-colors"
            >
              Back
            </button>
            <button
              onclick={loginWithNip07}
              disabled={isLoggingIn}
              class="flex-1 px-4 py-2 bg-purple-600 hover:bg-purple-700 disabled:bg-neutral-700 disabled:cursor-not-allowed text-white rounded-lg transition-colors font-semibold"
            >
              {isLoggingIn ? 'Connecting...' : 'Connect'}
            </button>
          </div>
        </div>
      {:else if loginMethod === 'nsec'}
        <div class="space-y-4">
          <div>
            <label class="block text-sm font-medium text-neutral-300 mb-2">
              Private Key (nsec)
            </label>
            <input
              type="password"
              bind:value={nsecInput}
              placeholder="nsec1..."
              class="w-full px-3 py-2 bg-neutral-800 border border-neutral-700 rounded-lg text-white placeholder-neutral-500 focus:outline-none focus:border-purple-500"
            />
          </div>

          {#if error}
            <div class="p-3 bg-red-500/10 border border-red-500/20 rounded-lg text-red-400 text-sm">
              {error}
            </div>
          {/if}

          <div class="p-3 bg-yellow-500/10 border border-yellow-500/20 rounded-lg text-yellow-400 text-sm">
            ⚠️ Your private key will be stored in browser localStorage. Use at your own risk.
          </div>

          <div class="flex gap-2">
            <button
              onclick={() => loginMethod = null}
              class="flex-1 px-4 py-2 bg-neutral-800 hover:bg-neutral-700 text-white rounded-lg transition-colors"
            >
              Back
            </button>
            <button
              onclick={loginWithNsec}
              disabled={isLoggingIn || !nsecInput.trim()}
              class="flex-1 px-4 py-2 bg-purple-600 hover:bg-purple-700 disabled:bg-neutral-700 disabled:cursor-not-allowed text-white rounded-lg transition-colors font-semibold"
            >
              {isLoggingIn ? 'Logging in...' : 'Login'}
            </button>
          </div>
        </div>
      {/if}
    </div>
  </div>
{/if}

// src/features/auth/LoginButton.tsx
import { useState } from 'react';
import { 
  useNDKCurrentUser,
  useNDKSessionLogin,
  useNDKSessionLogout,
  NDKNip07Signer,
  NDKPrivateKeySigner
} from '@nostr-dev-kit/ndk-hooks';
import { Button } from '@/components/ui/button';
import { User, LogOut, Key, Sparkles } from 'lucide-react';

export function LoginButton() {
  const currentUser = useNDKCurrentUser();
  const login = useNDKSessionLogin();
  const logout = useNDKSessionLogout();
  
  const [showOptions, setShowOptions] = useState(false);
  const [nsec, setNsec] = useState('');
  const [showNsecInput, setShowNsecInput] = useState(false);
  const [isConnecting, setIsConnecting] = useState(false);

  const handleExtensionLogin = async () => {
    setIsConnecting(true);
    try {
      if (!window.nostr) {
        throw new Error('No Nostr extension found. Please install Alby or nos2x.');
      }
      const signer = new NDKNip07Signer();
      await login(signer, true);
      setShowOptions(false);
    } catch (error) {
      console.error('Extension login failed:', error);
      alert(error instanceof Error ? error.message : 'Extension login failed');
    } finally {
      setIsConnecting(false);
    }
  };

  const handlePrivateKeyLogin = async () => {
    if (!nsec) return;
    setIsConnecting(true);
    try {
      const signer = new NDKPrivateKeySigner(nsec);
      await login(signer, true);
      localStorage.setItem('nostr_private_key', nsec);
      setNsec('');
      setShowNsecInput(false);
      setShowOptions(false);
    } catch (error) {
      console.error('Private key login failed:', error);
      alert('Invalid private key');
    } finally {
      setIsConnecting(false);
    }
  };

  const handleGenerateIdentity = async () => {
    setIsConnecting(true);
    try {
      const signer = NDKPrivateKeySigner.generate();
      await login(signer, true);
      const privateKey = signer.privateKey!;
      localStorage.setItem('nostr_private_key', privateKey);
      const user = await signer.user();
      alert(`New identity created!\nnpub: ${user.npub}\nnsec: ${privateKey}\n\nIMPORTANT: Save your nsec somewhere safe!`);
      setShowOptions(false);
    } catch (error) {
      console.error('Failed to generate identity:', error);
      alert('Failed to generate new identity');
    } finally {
      setIsConnecting(false);
    }
  };

  const handleLogout = () => {
    logout();
    localStorage.removeItem('nostr_private_key');
  };

  if (currentUser) {
    return (
      <div className="flex items-center gap-4">
        <button
          onClick={handleLogout}
          className="px-4 py-2 rounded-full bg-gray-100 hover:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700 transition-colors text-sm font-medium flex items-center gap-2"
        >
          <LogOut className="w-4 h-4" />
          <span className="hidden sm:inline">Logout</span>
        </button>
      </div>
    );
  }

  if (showOptions) {
    return (
      <div className="flex flex-col gap-2">
        <Button
          onClick={handleExtensionLogin}
          disabled={isConnecting}
          variant="default"
          size="sm"
        >
          <User className="w-4 h-4 mr-2" />
          Login with Extension
        </Button>
        
        {showNsecInput ? (
          <div className="flex gap-2">
            <input
              type="password"
              placeholder="Enter nsec or hex key"
              value={nsec}
              onChange={(e) => setNsec(e.target.value)}
              className="px-3 py-1 border rounded text-sm"
              disabled={isConnecting}
            />
            <Button
              onClick={handlePrivateKeyLogin}
              disabled={!nsec || isConnecting}
              size="sm"
              variant="outline"
            >
              Login
            </Button>
          </div>
        ) : (
          <Button
            onClick={() => setShowNsecInput(true)}
            disabled={isConnecting}
            variant="outline"
            size="sm"
          >
            <Key className="w-4 h-4 mr-2" />
            Login with Private Key
          </Button>
        )}
        
        <Button
          onClick={handleGenerateIdentity}
          disabled={isConnecting}
          variant="outline"
          size="sm"
        >
          <Sparkles className="w-4 h-4 mr-2" />
          Generate New Identity
        </Button>
        
        <Button
          onClick={() => {
            setShowOptions(false);
            setShowNsecInput(false);
            setNsec('');
          }}
          variant="ghost"
          size="sm"
          disabled={isConnecting}
        >
          Cancel
        </Button>
      </div>
    );
  }

  return (
    <button
      onClick={() => setShowOptions(true)}
      disabled={isConnecting}
      className="px-4 py-2 rounded-lg bg-white hover:bg-neutral-100 dark:bg-neutral-900 dark:hover:bg-neutral-800 text-neutral-900 dark:text-white border border-neutral-200 dark:border-neutral-700 transition-all text-sm font-medium flex items-center gap-2"
    >
      <User className="w-4 h-4" />
      <span className="hidden sm:inline">{isConnecting ? 'Connecting...' : 'Login'}</span>
      <span className="sm:hidden">{isConnecting ? '...' : 'Login'}</span>
    </button>
  );
}
