// src/features/invites/CreateInviteModal.tsx
import React, { useState } from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { CloseButton } from '@/components/invites/CloseButton';
import { ModalHeader } from '@/components/invites/ModalHeader';
import { User, Zap, Copy, Check } from 'lucide-react';
import { useNDK, useNDKCurrentUser } from '@nostr-dev-kit/ndk-hooks';
import { NDKEvent } from '@nostr-dev-kit/ndk';

interface CreateInviteModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const DEFAULT_WELCOME_MESSAGE = `Welcome to Voces! 🎉

I'm inviting you to join Voces, a new kind of social network where you own your identity and content. No algorithms, no ads, just authentic connections.

Looking forward to connecting with you on the open social web!`;

export function CreateInviteModal({ isOpen, onClose }: CreateInviteModalProps) {
  const { ndk } = useNDK();
  const user = useNDKCurrentUser();
  const [welcomeMessage, setWelcomeMessage] = useState(DEFAULT_WELCOME_MESSAGE);
  const [isPersonalized, setIsPersonalized] = useState(false);
  const [recipientName, setRecipientName] = useState('');
  const [cashuAmount, setCashuAmount] = useState('');
  const [inviteLink, setInviteLink] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isCopied, setIsCopied] = useState(false);

  const generateInvite = async () => {
    if (!ndk || !user) return;

    setIsGenerating(true);

    try {
      // Create invite event
      const inviteEvent = new NDKEvent(ndk);
      inviteEvent.kind = 420;
      inviteEvent.content = JSON.stringify({
        welcomeMessage,
        recipientName: isPersonalized ? recipientName : undefined,
        cashuToken: isPersonalized && cashuAmount ? `cashu:${cashuAmount}` : undefined,
        createdAt: Date.now(),
        inviter: user.pubkey
      });
      inviteEvent.tags = [
        ['p', user.pubkey],
        ['client', 'voces']
      ];

      await inviteEvent.sign();
      await inviteEvent.publish();

      // Generate invite link
      const inviteId = inviteEvent.id;
      const link = `${window.location.origin}/invite/${inviteId}`;
      setInviteLink(link);
    } catch (error) {
      console.error('Failed to generate invite:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(inviteLink);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
    } catch (error) {
      console.error('Failed to copy:', error);
    }
  };

  const handleClose = () => {
    // Reset form
    setWelcomeMessage(DEFAULT_WELCOME_MESSAGE);
    setIsPersonalized(false);
    setRecipientName('');
    setCashuAmount('');
    setInviteLink('');
    onClose();
  };

  return createPortal(
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 bg-black/50 flex items-center justify-center z-[9999] p-4"
          onClick={handleClose}
        >
          <motion.div
            initial={{ scale: 0.9, y: 20 }}
            animate={{ scale: 1, y: 0 }}
            exit={{ scale: 0.9, y: 20 }}
            transition={{ type: 'spring', damping: 20, stiffness: 300 }}
            className="bg-white dark:bg-black rounded-2xl shadow-xl w-full max-w-lg relative p-8"
            onClick={(e) => e.stopPropagation()}
          >
            <CloseButton onClick={handleClose} />
            <ModalHeader
              title="Create an Invite"
              subtitle="Invite someone to join Voces with a personal message"
            />

            {!inviteLink ? (
              <div className="space-y-6">
                {/* Welcome Message */}
                <div>
                  <label className="block text-sm font-medium text-neutral-700 dark:text-neutral-300 mb-2">
                    Welcome Message
                  </label>
                  <textarea
                    value={welcomeMessage}
                    onChange={(e) => setWelcomeMessage(e.target.value)}
                    rows={6}
                    className="w-full px-4 py-3 border border-neutral-300 dark:border-neutral-700 rounded-xl
                             bg-white dark:bg-neutral-900 text-neutral-900 dark:text-white
                             focus:ring-2 focus:ring-orange-500 focus:border-transparent resize-none"
                    placeholder="Write a welcome message..."
                  />
                </div>

                {/* Personalization Toggle */}
                <div className="flex items-center space-x-3">
                  <input
                    type="checkbox"
                    id="personalize"
                    checked={isPersonalized}
                    onChange={(e) => setIsPersonalized(e.target.checked)}
                    className="w-5 h-5 text-orange-600 border-neutral-300 rounded focus:ring-orange-500"
                  />
                  <label
                    htmlFor="personalize"
                    className="text-sm font-medium text-neutral-700 dark:text-neutral-300 cursor-pointer"
                  >
                    Personalize this invite
                  </label>
                </div>

                {/* Personalization Options */}
                {isPersonalized && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: 'auto' }}
                    exit={{ opacity: 0, height: 0 }}
                    className="space-y-4 border-l-4 border-orange-500 pl-4"
                  >
                    <div>
                      <label className="flex items-center text-sm font-medium text-neutral-700 dark:text-neutral-300 mb-2">
                        <User className="w-4 h-4 mr-2" />
                        Recipient's Name
                      </label>
                      <input
                        type="text"
                        value={recipientName}
                        onChange={(e) => setRecipientName(e.target.value)}
                        className="w-full px-4 py-2 border border-neutral-300 dark:border-neutral-700 rounded-xl
                                 bg-white dark:bg-neutral-900 text-neutral-900 dark:text-white
                                 focus:ring-2 focus:ring-orange-500 focus:border-transparent"
                        placeholder="John Doe"
                      />
                    </div>

                    <div>
                      <label className="flex items-center text-sm font-medium text-neutral-700 dark:text-neutral-300 mb-2">
                        <Zap className="w-4 h-4 mr-2" />
                        Include Cashu Token (sats)
                      </label>
                      <input
                        type="number"
                        value={cashuAmount}
                        onChange={(e) => setCashuAmount(e.target.value)}
                        className="w-full px-4 py-2 border border-neutral-300 dark:border-neutral-700 rounded-xl
                                 bg-white dark:bg-neutral-900 text-neutral-900 dark:text-white
                                 focus:ring-2 focus:ring-orange-500 focus:border-transparent"
                        placeholder="Amount in sats (optional)"
                      />
                      <p className="mt-1 text-xs text-neutral-500 dark:text-neutral-400">
                        Add sats to help them get started on Nostr
                      </p>
                    </div>
                  </motion.div>
                )}

                {/* Generate Button */}
                <button
                  onClick={generateInvite}
                  disabled={isGenerating || !welcomeMessage.trim()}
                  className="w-full py-3 px-4 bg-orange-600 hover:bg-orange-700 disabled:bg-neutral-400
                           text-white font-semibold rounded-xl transition-colors
                           disabled:cursor-not-allowed flex items-center justify-center"
                >
                  {isGenerating ? (
                    <>
                      <div className="animate-spin rounded-full h-5 w-5 border-2 border-white border-t-transparent mr-2" />
                      Generating Invite...
                    </>
                  ) : (
                    'Generate Invite Link'
                  )}
                </button>
              </div>
            ) : (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="space-y-6"
              >
                <div className="text-center py-8">
                  <div className="w-16 h-16 bg-green-100 dark:bg-green-900/30 rounded-full
                                flex items-center justify-center mx-auto mb-4">
                    <Check className="w-8 h-8 text-green-600 dark:text-green-400" />
                  </div>
                  <h3 className="text-lg font-semibold text-neutral-900 dark:text-white mb-2">
                    Invite Created!
                  </h3>
                  <p className="text-sm text-neutral-600 dark:text-neutral-400">
                    {isPersonalized && recipientName ?
                      `Your personalized invite for ${recipientName} is ready` :
                      'Your invite link is ready to share'}
                  </p>
                </div>

                <div className="bg-neutral-100 dark:bg-neutral-900 rounded-xl p-4">
                  <div className="flex items-center space-x-2">
                    <input
                      type="text"
                      value={inviteLink}
                      readOnly
                      className="flex-1 bg-transparent text-sm text-neutral-700 dark:text-neutral-300
                               outline-none truncate"
                    />
                    <button
                      onClick={copyToClipboard}
                      className="px-3 py-1.5 bg-orange-600 hover:bg-orange-700 text-white
                               rounded-lg transition-colors flex items-center space-x-1 text-sm"
                    >
                      {isCopied ? (
                        <>
                          <Check className="w-4 h-4" />
                          <span>Copied!</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-4 h-4" />
                          <span>Copy</span>
                        </>
                      )}
                    </button>
                  </div>
                </div>

                <div className="flex space-x-3">
                  <button
                    onClick={() => setInviteLink('')}
                    className="flex-1 py-2.5 px-4 border border-neutral-300 dark:border-neutral-700
                             text-neutral-700 dark:text-neutral-300 font-medium rounded-xl
                             hover:bg-neutral-50 dark:hover:bg-neutral-900 transition-colors"
                  >
                    Create Another
                  </button>
                  <button
                    onClick={handleClose}
                    className="flex-1 py-2.5 px-4 bg-orange-600 hover:bg-orange-700
                             text-white font-medium rounded-xl transition-colors"
                  >
                    Done
                  </button>
                </div>
              </motion.div>
            )}
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>,
    document.body
  );
}

// src/lib/components/invite/CreateInviteModal.svelte
<script lang="ts">
	import { ndk } from '$lib/ndk.svelte';
	import { NDKEvent, NDKRelaySet, type NDKRelay } from '@nostr-dev-kit/ndk';
	import { settings } from '$lib/stores/settings.svelte';
	import { useRelayInfoCached } from '$lib/utils/relayInfo.svelte';
	import { clickOutside } from '$lib/utils/clickOutside';
	import {
		generateDTag,
		generateEncryptionKey,
		encryptInvitePayload
	} from '$lib/utils/inviteEncryption';

	interface Props {
		isOpen: boolean;
		onClose: () => void;
	}

	let { isOpen = $bindable(), onClose }: Props = $props();

	const DEFAULT_WELCOME_MESSAGE = `Welcome to Agora! 🎉

I'm inviting you to join Agora, a new kind of social network where you own your identity and content. No algorithms, no ads, just authentic connections.

Looking forward to connecting with you on the open social web!`;

	let welcomeMessage = $state(DEFAULT_WELCOME_MESSAGE);
	let isPersonalized = $state(false);
	let recipientName = $state('');
	let cashuAmount = $state('');
	let inviteLink = $state('');
	let isGenerating = $state(false);
	let isCopied = $state(false);
	let selectedRelayUrls = $state<string[]>([]);
	let isRelayDropdownOpen = $state(false);

	// Get enabled write relays
	const writeRelays = $derived(settings.relays.filter(r => r.enabled && r.write));

	// Initialize with selected relay if one is set
	$effect(() => {
		if (isOpen && settings.selectedRelay && selectedRelayUrls.length === 0) {
			// Only preselect if the selected relay is also a write relay
			const isWriteRelay = writeRelays.some(r => r.url === settings.selectedRelay);
			if (isWriteRelay) {
				selectedRelayUrls = [settings.selectedRelay];
			}
		}
	});

	function toggleRelay(url: string) {
		if (selectedRelayUrls.includes(url)) {
			selectedRelayUrls = selectedRelayUrls.filter(r => r !== url);
		} else {
			selectedRelayUrls = [...selectedRelayUrls, url];
		}
	}

	const selectedRelayInfo = $derived.by(() => {
		if (selectedRelayUrls.length === 0) return null;
		if (selectedRelayUrls.length === 1) {
			return {
				url: selectedRelayUrls[0],
				info: useRelayInfoCached(selectedRelayUrls[0])
			};
		}
		return null;
	});

	const selectedRelayName = $derived.by(() => {
		if (selectedRelayUrls.length === 0) return 'Select relay...';
		if (selectedRelayUrls.length === 1) {
			const relayInfo = useRelayInfoCached(selectedRelayUrls[0]);
			return relayInfo.info?.name || selectedRelayUrls[0].replace('wss://', '').replace('ws://', '');
		}
		return `${selectedRelayUrls.length} relays selected`;
	});

	async function generateInvite() {
		if (!ndk.$currentUser) {
			console.error("No user logged in");
			return;
		}

		if (selectedRelayUrls.length === 0) {
			alert('Please select at least one relay to publish the invite to.');
			return;
		}

		isGenerating = true;

		try {
			// Generate d-tag and encryption key
			const dTag = generateDTag();
			const encryptionKey = isPersonalized ? generateEncryptionKey() : '';

			// Create payload
			const payload = {
				welcomeMessage,
				recipientName: isPersonalized ? recipientName : undefined,
				cashuToken: isPersonalized && cashuAmount ? `cashu:${cashuAmount}` : undefined,
				createdAt: Date.now(),
				inviter: ndk.$currentUser.pubkey,
			};

			// Encrypt payload if personalized, otherwise just JSON
			const content = isPersonalized
				? await encryptInvitePayload(JSON.stringify(payload), encryptionKey)
				: JSON.stringify(payload);

			// Create invite event (kind 513 - Agora Invite)
			const inviteEvent = new NDKEvent(ndk);
			inviteEvent.kind = 513;
			inviteEvent.content = content;
			inviteEvent.tags = [
				['d', dTag]
			];
			inviteEvent.isProtected = true;

			await inviteEvent.sign();

			// Mark as protected before publishing
			inviteEvent.isProtected = true;

			console.log('Publishing invite event to selected relays...', inviteEvent.id, selectedRelayUrls);

			// Publish to specific relays only
			const relays = new Set<NDKRelay>();
			for (const url of selectedRelayUrls) {
				const relay = ndk.pool.getRelay(url, true);
				if (relay) {
					relays.add(relay);
				}
			}

			const relaySet = new NDKRelaySet(relays, ndk);
			await inviteEvent.publish(relaySet);

			// Generate invite link: /i/{dTag}{encryptionKey}
			const code = isPersonalized ? `${dTag}${encryptionKey}` : dTag;
			const link = `${window.location.origin}/i/${code}`;
			inviteLink = link;
			console.log('Invite created:', link);
		} catch (error) {
			console.error('Failed to generate invite:', error);
			alert('Failed to generate invite. Check console for details.');
		} finally {
			isGenerating = false;
		}
	}

	async function copyToClipboard() {
		try {
			await navigator.clipboard.writeText(inviteLink);
			isCopied = true;
			setTimeout(() => (isCopied = false), 2000);
		} catch (error) {
			console.error('Failed to copy:', error);
		}
	}

	function handleClose() {
		// Reset form
		welcomeMessage = DEFAULT_WELCOME_MESSAGE;
		isPersonalized = false;
		recipientName = '';
		cashuAmount = '';
		inviteLink = '';
		selectedRelayUrls = [];
		isRelayDropdownOpen = false;
		onClose();
	}

	function handleRelayDropdownClickOutside() {
		isRelayDropdownOpen = false;
	}

	function handleBackdropClick(e: MouseEvent) {
		if (e.target === e.currentTarget) {
			handleClose();
		}
	}
</script>

{#if isOpen}
	<div
		class="fixed inset-0 bg-black/50 flex items-center justify-center z-[9999] p-4"
		onclick={handleBackdropClick}
		role="presentation"
	>
		<div class="bg-white dark:bg-black rounded-2xl shadow-xl w-full max-w-lg relative p-8">
			<button
				onclick={handleClose}
				class="absolute top-4 right-4 p-2 hover:bg-neutral-100 dark:hover:bg-neutral-900 rounded-lg transition-colors"
			>
				<svg class="w-5 h-5 text-neutral-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
				</svg>
			</button>

			<div class="mb-6">
				<h2 class="text-2xl font-bold text-neutral-900 dark:text-white mb-1">Create an Invite</h2>
				<p class="text-sm text-neutral-600 dark:text-neutral-400">
					Invite someone to join Agora with a personal message
				</p>
			</div>

			{#if !inviteLink}
				<div class="space-y-6">
					<!-- Welcome Message -->
					<div>
						<label
							for="welcome-message"
							class="block text-sm font-medium text-neutral-700 dark:text-neutral-300 mb-2"
						>
							Welcome Message
						</label>
						<textarea
							id="welcome-message"
							bind:value={welcomeMessage}
							rows="6"
							class="w-full px-4 py-3 border border-neutral-300 dark:border-neutral-700 rounded-xl bg-white dark:bg-neutral-900 text-neutral-900 dark:text-white focus:ring-2 focus:ring-orange-500 focus:border-transparent resize-none"
							placeholder="Write a welcome message..."
						></textarea>
					</div>

					<!-- Relay Selection -->
					<div class="relative">
						<label class="block text-sm font-medium text-neutral-700 dark:text-neutral-300 mb-2">
							Publish to Relay
						</label>
						<button
							type="button"
							onclick={() => isRelayDropdownOpen = !isRelayDropdownOpen}
							class="w-full px-4 py-2.5 text-left rounded-lg bg-neutral-800/50 text-neutral-300 hover:bg-neutral-800 transition-colors flex items-center gap-3 group"
						>
							{#if selectedRelayUrls.length === 0}
								<div class="w-6 h-6 rounded bg-neutral-700 flex items-center justify-center flex-shrink-0">
									<svg class="w-4 h-4 text-neutral-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01" />
									</svg>
								</div>
								<span class="text-sm text-neutral-500 flex-1">Select relay...</span>
							{:else if selectedRelayUrls.length === 1 && selectedRelayInfo}
								{#if selectedRelayInfo.info.info?.icon}
									<img src={selectedRelayInfo.info.info.icon} alt="" class="w-6 h-6 rounded flex-shrink-0" />
								{:else}
									<div class="w-6 h-6 rounded bg-neutral-700 flex items-center justify-center flex-shrink-0">
										<svg class="w-4 h-4 text-neutral-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01" />
										</svg>
									</div>
								{/if}
								<span class="text-sm text-neutral-300 flex-1">{selectedRelayName}</span>
							{:else}
								<div class="w-6 h-6 rounded bg-neutral-700 flex items-center justify-center flex-shrink-0">
									<svg class="w-4 h-4 text-neutral-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01" />
									</svg>
								</div>
								<span class="text-sm text-neutral-300 flex-1">{selectedRelayUrls.length} relays selected</span>
							{/if}
							<svg class="w-4 h-4 text-neutral-500 transition-transform flex-shrink-0 {isRelayDropdownOpen ? 'rotate-180' : ''}" fill="none" stroke="currentColor" viewBox="0 0 24 24">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
							</svg>
						</button>

						{#if isRelayDropdownOpen}
							<div
								use:clickOutside={handleRelayDropdownClickOutside}
								class="absolute z-10 mt-1 w-full bg-white dark:bg-neutral-900 border border-neutral-300 dark:border-neutral-700 rounded-xl shadow-lg max-h-64 overflow-y-auto"
							>
								{#if writeRelays.length === 0}
									<p class="text-sm text-neutral-500 text-center py-4">No write relays configured</p>
								{:else}
									{#each writeRelays as relay (relay.url)}
										{@const relayInfo = useRelayInfoCached(relay.url)}
										<button
											type="button"
											onclick={() => {
												toggleRelay(relay.url);
											}}
											class="w-full flex items-center gap-3 p-3 hover:bg-neutral-100 dark:hover:bg-neutral-800 cursor-pointer transition-colors text-left"
										>
											<input
												type="checkbox"
												checked={selectedRelayUrls.includes(relay.url)}
												class="w-4 h-4 text-orange-600 border-neutral-300 rounded focus:ring-orange-500 pointer-events-none"
											/>
											{#if relayInfo.info?.icon}
												<img src={relayInfo.info.icon} alt="" class="w-5 h-5 rounded flex-shrink-0" />
											{:else}
												<div class="w-5 h-5 rounded bg-neutral-300 dark:bg-neutral-700 flex items-center justify-center flex-shrink-0">
													<svg class="w-3 h-3 text-neutral-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
														<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01" />
													</svg>
												</div>
											{/if}
											<span class="text-sm text-neutral-700 dark:text-neutral-300 flex-1 truncate">
												{relayInfo.info?.name || relay.url.replace('wss://', '').replace('ws://', '')}
											</span>
										</button>
									{/each}
								{/if}
							</div>
						{/if}

						{#if selectedRelayUrls.length > 1}
							<p class="mt-1 text-xs text-neutral-500 dark:text-neutral-400">
								{selectedRelayUrls.length} relays selected
							</p>
						{/if}
					</div>

					<!-- Personalization Toggle -->
					<div class="flex items-center space-x-3">
						<input
							type="checkbox"
							id="personalize"
							bind:checked={isPersonalized}
							class="w-5 h-5 text-orange-600 border-neutral-300 rounded focus:ring-orange-500"
						/>
						<label
							for="personalize"
							class="text-sm font-medium text-neutral-700 dark:text-neutral-300 cursor-pointer"
						>
							Personalize this invite
						</label>
					</div>

					<!-- Personalization Options -->
					{#if isPersonalized}
						<div class="space-y-4 border-l-4 border-orange-500 pl-4">
							<div>
								<label
									for="recipient-name"
									class="flex items-center text-sm font-medium text-neutral-700 dark:text-neutral-300 mb-2"
								>
									<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
									</svg>
									Recipient's Name
								</label>
								<input
									id="recipient-name"
									type="text"
									bind:value={recipientName}
									class="w-full px-4 py-2 border border-neutral-300 dark:border-neutral-700 rounded-xl bg-white dark:bg-neutral-900 text-neutral-900 dark:text-white focus:ring-2 focus:ring-orange-500 focus:border-transparent"
									placeholder="John Doe"
								/>
							</div>

							<div>
								<label
									for="cashu-amount"
									class="flex items-center text-sm font-medium text-neutral-700 dark:text-neutral-300 mb-2"
								>
									<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
									</svg>
									Include Cashu Token (sats)
								</label>
								<input
									id="cashu-amount"
									type="number"
									bind:value={cashuAmount}
									class="w-full px-4 py-2 border border-neutral-300 dark:border-neutral-700 rounded-xl bg-white dark:bg-neutral-900 text-neutral-900 dark:text-white focus:ring-2 focus:ring-orange-500 focus:border-transparent"
									placeholder="Amount in sats (optional)"
								/>
								<p class="mt-1 text-xs text-neutral-500 dark:text-neutral-400">
									Add sats to help them get started on Nostr
								</p>
							</div>
						</div>
					{/if}

					<!-- Generate Button -->
					<button
						onclick={generateInvite}
						disabled={isGenerating || !welcomeMessage.trim() || selectedRelayUrls.length === 0}
						class="w-full py-3 px-4 bg-orange-600 hover:bg-orange-700 disabled:bg-neutral-400 text-white font-semibold rounded-xl transition-colors disabled:cursor-not-allowed flex items-center justify-center"
					>
						{#if isGenerating}
							<div
								class="animate-spin rounded-full h-5 w-5 border-2 border-white border-t-transparent mr-2"
							></div>
							Generating Invite...
						{:else}
							Generate Invite Link
						{/if}
					</button>
				</div>
			{:else}
				<div class="space-y-6">
					<div class="text-center py-8">
						<div
							class="w-16 h-16 bg-green-100 dark:bg-green-900/30 rounded-full flex items-center justify-center mx-auto mb-4"
						>
							<svg class="w-8 h-8 text-green-600 dark:text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
							</svg>
						</div>
						<h3 class="text-lg font-semibold text-neutral-900 dark:text-white mb-2">
							Invite Created!
						</h3>
						<p class="text-sm text-neutral-600 dark:text-neutral-400">
							{isPersonalized && recipientName
								? `Your personalized invite for ${recipientName} is ready`
								: 'Your invite link is ready to share'}
						</p>
					</div>

					<div class="bg-neutral-100 dark:bg-neutral-900 rounded-xl p-4">
						<div class="flex items-center space-x-2">
							<input
								type="text"
								value={inviteLink}
								readonly
								class="flex-1 bg-transparent text-sm text-neutral-700 dark:text-neutral-300 outline-none truncate"
							/>
							<button
								onclick={copyToClipboard}
								class="px-3 py-1.5 bg-orange-600 hover:bg-orange-700 text-white rounded-lg transition-colors flex items-center space-x-1 text-sm"
							>
								{#if isCopied}
									<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
									</svg>
									<span>Copied!</span>
								{:else}
									<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
									</svg>
									<span>Copy</span>
								{/if}
							</button>
						</div>
					</div>

					<div class="flex space-x-3">
						<button
							onclick={() => (inviteLink = '')}
							class="flex-1 py-2.5 px-4 border border-neutral-300 dark:border-neutral-700 text-neutral-700 dark:text-neutral-300 font-medium rounded-xl hover:bg-neutral-50 dark:hover:bg-neutral-900 transition-colors"
						>
							Create Another
						</button>
						<button
							onclick={handleClose}
							class="flex-1 py-2.5 px-4 bg-orange-600 hover:bg-orange-700 text-white font-medium rounded-xl transition-colors"
						>
							Done
						</button>
					</div>
				</div>
			{/if}
		</div>
	</div>
{/if}
