// src/pages/onboarding/Step2FollowPacks.tsx
import { useState, useEffect } from 'react';
import { NDKFollowPack, NDKEvent } from '@nostr-dev-kit/ndk';
import { useNDK } from '@nostr-dev-kit/ndk-hooks';
import { nip19 } from 'nostr-tools';
import { FollowPackCard } from '@/features/followPacks/components/FollowPackCard';
import { FOLLOW_PACK_ADDRESSES, COMMUNITY_METADATA } from '@/config/followPacks';

interface Step2FollowPacksProps {
  selectedCommunity: string | null;
  selectedPacks: string[];
  onSelectPacks: (packs: string[]) => void;
  onNext: () => void;
}

export function Step2FollowPacks({ selectedCommunity, selectedPacks, onSelectPacks, onNext }: Step2FollowPacksProps) {
  const [loading, setLoading] = useState(true);
  const [followPacks, setFollowPacks] = useState<NDKFollowPack[]>([]);
  const { ndk } = useNDK();

  // Get follow pack addresses for the selected community
  const communityKey = selectedCommunity || 'venezuela';
  const packAddresses = FOLLOW_PACK_ADDRESSES[communityKey] || FOLLOW_PACK_ADDRESSES.venezuela || FOLLOW_PACK_ADDRESSES.default;
  const communityInfo = COMMUNITY_METADATA[communityKey] || COMMUNITY_METADATA.venezuela;

  // Fetch follow packs from naddr
  useEffect(() => {
    async function fetchPacks() {
      if (!ndk) return;

      setLoading(true);
      const packs: NDKFollowPack[] = [];

      for (const naddr of packAddresses) {
        try {
          // Decode the naddr
          const decoded = nip19.decode(naddr);
          if (decoded.type !== 'naddr') continue;

          const { identifier, pubkey, kind, relays } = decoded.data;

          // Fetch the event
          const filter = {
            kinds: [kind],
            authors: [pubkey],
            '#d': [identifier],
          };

          const event = await ndk.fetchEvent(filter, { closeOnEose: true }, relays ? new Set(relays) : undefined);

          if (event) {
            // Convert NDKEvent to NDKFollowPack
            const pack = NDKFollowPack.from(event as NDKEvent);
            packs.push(pack);
          }
        } catch (err) {
          console.error(`Error fetching pack ${naddr}:`, err);
        }
      }

      setFollowPacks(packs);
      setLoading(false);
    }

    fetchPacks();
  }, [ndk, packAddresses]);

  const handlePackClick = (pack: NDKFollowPack, e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();

    const packId = pack.encode();
    if (selectedPacks.includes(packId)) {
      onSelectPacks(selectedPacks.filter(id => id !== packId));
    } else {
      onSelectPacks([...selectedPacks, packId]);
    }
  };

  const handleNext = async () => {
    if (selectedPacks.length === 0) return;
    onNext();
  };


  return (
    <div className="flex min-h-screen">
      {/* Left Panel - Visual */}
      <div className="hidden lg:block w-1/2 relative">
        <img
          src="https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=1200&q=80"
          alt="Community leaders"
          className="absolute inset-0 w-full h-full object-cover"
        />
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-black/30 to-black/70" />
        <div className="absolute bottom-0 left-0 right-0 p-12">
          <div className="mb-8">
            <p className="text-3xl text-white/90 italic leading-relaxed">
              &quot;We&apos;re not just surviving—we&apos;re building the future our community deserves. One voice at a time.&quot;
            </p>
          </div>
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 bg-white/20 backdrop-blur rounded-full flex items-center justify-center text-white font-semibold">
              MR
            </div>
            <div className="text-white">
              <div className="font-semibold">María Rodríguez</div>
              <div className="text-sm opacity-75">Community Organizer · Caracas</div>
            </div>
          </div>
        </div>
      </div>

      {/* Right Panel - Follow Packs Grid */}
      <div className="w-full lg:w-1/2 flex items-center justify-center p-4 sm:p-6 lg:p-12">
        <div className="max-w-xl w-full">
          <div className="mb-6 lg:mb-8">
            <h1 className="text-2xl lg:text-3xl font-bold mb-2 lg:mb-3">Build Your Network</h1>
            <p className="text-sm lg:text-base text-neutral-600 dark:text-neutral-400">
              Follow curated packs from the {communityInfo.name} community
            </p>
          </div>

          {loading ? (
            <div className="space-y-2 mb-8">
              {[1, 2, 3, 4].map(i => (
                <div key={i} className="h-20 bg-neutral-100 dark:bg-black rounded-xl animate-pulse" />
              ))}
            </div>
          ) : (
            <>
              {/* Follow Pack List */}
              <div className="space-y-2 mb-6 lg:mb-8 max-h-[50vh] lg:max-h-[60vh] overflow-y-auto p-2 -m-2">
                {followPacks.map((pack) => {
                  const isSelected = selectedPacks.includes(pack.encode());
                  return (
                    <div
                      key={pack.encode()}
                      onClick={(e) => handlePackClick(pack, e)}
                      className={`
                        relative cursor-pointer rounded-xl transition-all
                        ${isSelected
                          ? 'ring-2 ring-orange-500 bg-orange-50 dark:bg-orange-950/20'
                          : ''
                        }
                      `}
                    >
                      {/* Wrapper div to intercept clicks */}
                      <div
                        className="pointer-events-none"
                        onClick={(e) => e.stopPropagation()}
                      >
                        <FollowPackCard pack={pack} variant="compact" />
                      </div>

                      {/* Selection checkmark */}
                      {isSelected && (
                        <div className="absolute top-1/2 right-4 -translate-y-1/2 bg-orange-500 text-white rounded-full p-1.5 z-10">
                          <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                          </svg>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>

              {followPacks.length === 0 && (
                <div className="text-center py-8 text-neutral-500 dark:text-neutral-400">
                  No follow packs available for this community yet
                </div>
              )}
            </>
          )}

          <button
            onClick={handleNext}
            disabled={selectedPacks.length === 0 || loading}
            className={`
              w-full py-3 lg:py-4 px-6 rounded-lg font-medium transition-all text-sm lg:text-base
              ${selectedPacks.length > 0 && !loading
                ? 'bg-black dark:bg-white text-white dark:text-black hover:bg-neutral-800 dark:hover:bg-neutral-200'
                : 'bg-neutral-100 dark:bg-black text-neutral-400 cursor-not-allowed'
              }
            `}
          >
            Continue →
          </button>
        </div>
      </div>
    </div>
  );
}

// src/lib/pages/onboarding/Step2FollowPacks.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { ndk } from '$lib/ndk.svelte';
  import { nip19 } from 'nostr-tools';
  import { type NDKFollowPack, NDKEvent } from '@nostr-dev-kit/ndk';
  import { FOLLOW_PACK_ADDRESSES, COMMUNITY_METADATA } from '$lib/config/followPacks';

  interface Props {
    selectedCommunity: string | null;
    selectedPacks: string[];
    onSelectPacks: (packs: string[]) => void;
    onNext: () => void;
  }

  let { selectedCommunity, selectedPacks, onSelectPacks, onNext }: Props = $props();

  let loading = $state(true);
  let followPacks = $state<NDKFollowPack[]>([]);

  const communityKey = selectedCommunity || 'venezuela';
  const packAddresses = FOLLOW_PACK_ADDRESSES[communityKey] || FOLLOW_PACK_ADDRESSES.venezuela || FOLLOW_PACK_ADDRESSES.default;
  const communityInfo = COMMUNITY_METADATA[communityKey] || COMMUNITY_METADATA.venezuela;

  onMount(async () => {
    loading = true;
    const packs: NDKFollowPack[] = [];

    for (const naddr of packAddresses) {
      try {
        const decoded = nip19.decode(naddr);
        if (decoded.type !== 'naddr') continue;

        const { identifier, pubkey, kind, relays } = decoded.data;

        const filter = {
          kinds: [kind],
          authors: [pubkey],
          '#d': [identifier],
        };

        const event = await ndk.fetchEvent(filter, { closeOnEose: true }, relays ? new Set(relays) : undefined);

        if (event) {
          const pack = (await import('@nostr-dev-kit/ndk')).NDKFollowPack.from(event as NDKEvent);
          packs.push(pack);
        }
      } catch (err) {
        console.error(`Error fetching pack ${naddr}:`, err);
      }
    }

    followPacks = packs;
    loading = false;
  });

  function handlePackClick(pack: NDKFollowPack) {
    const packId = pack.encode();
    if (selectedPacks.includes(packId)) {
      onSelectPacks(selectedPacks.filter(id => id !== packId));
    } else {
      onSelectPacks([...selectedPacks, packId]);
    }
  }

  function handleNext() {
    if (selectedPacks.length === 0) return;
    onNext();
  }
</script>

<div class="flex min-h-screen">
  <!-- Left Panel - Visual -->
  <div class="hidden lg:block w-1/2 relative">
    <img
      src="https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=1200&q=80"
      alt="Community leaders"
      class="absolute inset-0 w-full h-full object-cover"
    />
    <div class="absolute inset-0 bg-gradient-to-b from-transparent via-black/30 to-black/70" />
    <div class="absolute bottom-0 left-0 right-0 p-12">
      <div class="mb-8">
        <p class="text-3xl text-white/90 italic leading-relaxed">
          "We're not just surviving—we're building the future our community deserves. One voice at a time."
        </p>
      </div>
      <div class="flex items-center gap-4">
        <div class="w-12 h-12 bg-white/20 backdrop-blur rounded-full flex items-center justify-center text-white font-semibold">
          MR
        </div>
        <div class="text-white">
          <div class="font-semibold">María Rodríguez</div>
          <div class="text-sm opacity-75">Community Organizer · Caracas</div>
        </div>
      </div>
    </div>
  </div>

  <!-- Right Panel - Follow Packs Grid -->
  <div class="w-full lg:w-1/2 flex items-center justify-center p-4 sm:p-6 lg:p-12">
    <div class="max-w-xl w-full">
      <div class="mb-6 lg:mb-8">
        <h1 class="text-2xl lg:text-3xl font-bold mb-2 lg:mb-3">Build Your Network</h1>
        <p class="text-sm lg:text-base text-neutral-600 dark:text-neutral-400">
          Follow curated packs from the {communityInfo.name} community
        </p>
      </div>

      {#if loading}
        <div class="space-y-2 mb-8">
          {#each [1, 2, 3, 4] as i (i)}
            <div class="h-20 bg-neutral-100 dark:bg-black rounded-xl animate-pulse" />
          {/each}
        </div>
      {:else}
        <!-- Follow Pack List -->
        <div class="space-y-2 mb-6 lg:mb-8 max-h-[50vh] lg:max-h-[60vh] overflow-y-auto p-2 -m-2">
          {#each followPacks as pack (pack.encode())}
            {@const isSelected = selectedPacks.includes(pack.encode())}
            <button
              onclick={() => handlePackClick(pack)}
              class={`
                relative w-full cursor-pointer rounded-xl transition-all text-left
                flex gap-3 sm:gap-4 p-3 sm:p-4 bg-white dark:bg-black hover:bg-neutral-50 dark:hover:bg-neutral-900 border border-neutral-200 dark:border-neutral-800
                ${isSelected ? 'ring-2 ring-orange-500 bg-orange-50 dark:bg-orange-950/20' : ''}
              `}
            >
              <!-- Image -->
              {#if pack.image}
                <img
                  src={pack.image}
                  alt={pack.title}
                  class="w-16 h-16 sm:w-20 sm:h-20 rounded-lg object-cover flex-shrink-0"
                />
              {:else}
                <div class="w-16 h-16 sm:w-20 sm:h-20 rounded-lg bg-gradient-to-br from-orange-500 to-red-500 flex items-center justify-center flex-shrink-0">
                  <span class="text-xl sm:text-2xl">📦</span>
                </div>
              {/if}

              <!-- Content -->
              <div class="flex-1 min-w-0">
                <h4 class="font-semibold text-sm sm:text-base text-neutral-900 dark:text-neutral-100 truncate">
                  {pack.title}
                </h4>
                {#if pack.description}
                  <p class="text-xs sm:text-sm text-neutral-600 dark:text-neutral-400 line-clamp-1 sm:truncate">
                    {pack.description}
                  </p>
                {/if}
                <div class="flex items-center gap-2 sm:gap-3 mt-1 sm:mt-2">
                  <span class="text-[10px] sm:text-xs text-neutral-500 dark:text-neutral-400">
                    {pack.pubkeys?.length || 0} members
                  </span>
                </div>
              </div>

              <!-- Selection checkmark -->
              {#if isSelected}
                <div class="absolute top-1/2 right-4 -translate-y-1/2 bg-orange-500 text-white rounded-full p-1.5 z-10">
                  <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
                  </svg>
                </div>
              {/if}
            </button>
          {/each}
        </div>

        {#if followPacks.length === 0}
          <div class="text-center py-8 text-neutral-500 dark:text-neutral-400">
            No follow packs available for this community yet
          </div>
        {/if}
      {/if}

      <button
        onclick={handleNext}
        disabled={selectedPacks.length === 0 || loading}
        class={`
          w-full py-3 lg:py-4 px-6 rounded-lg font-medium transition-all text-sm lg:text-base
          ${selectedPacks.length > 0 && !loading
            ? 'bg-black dark:bg-white text-white dark:text-black hover:bg-neutral-800 dark:hover:bg-neutral-200'
            : 'bg-neutral-100 dark:bg-black text-neutral-400 cursor-not-allowed'
          }
        `}
      >
        Continue →
      </button>
    </div>
  </div>
</div>
