// src/features/articles/components/ArticleHeader.tsx
import { NDKArticle } from '@nostr-dev-kit/ndk';
import { useProfile } from '@nostr-dev-kit/ndk-hooks';
import { UserAvatar } from '@/components/ui/UserAvatar';
import { FollowButton } from '@/components/ui/FollowButton';
import { useNDKCurrentUser } from '@nostr-dev-kit/ndk-hooks';
import { Link } from 'react-router-dom';
import { nip19 } from 'nostr-tools';

interface ArticleHeaderProps {
  article: NDKArticle;
}

export function ArticleHeader({ article }: ArticleHeaderProps) {
  const authorProfile = useProfile(article.pubkey);
  const currentUser = useNDKCurrentUser();
  const title = article.title || 'Untitled';
  const summary = article.summary;
  const publishedAt = article.published_at;

  // Estimate reading time based on content length
  const wordsPerMinute = 200;
  const words = article.content?.split(/\s+/).length || 0;
  const readingTime = Math.ceil(words / wordsPerMinute);

  const authorName = authorProfile?.name || authorProfile?.displayName || 'Anonymous';
  const authorBio = authorProfile?.about;

  const isOwnArticle = currentUser?.pubkey === article.pubkey;
  const npub = nip19.npubEncode(article.pubkey);

  return (
    <div className="mb-12">
      {/* Title */}
      <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-neutral-900 dark:text-white mb-6 leading-[1.1] tracking-tight font-serif">
        {title}
      </h1>

      {/* Summary */}
      {summary && (
        <p className="text-xl sm:text-2xl text-neutral-600 dark:text-neutral-400 mb-8 leading-relaxed font-light">
          {summary}
        </p>
      )}

      {/* Author Section */}
      <div className="flex items-start sm:items-center gap-4 mb-8">
        <Link to={`/p/${npub}`} className="flex-shrink-0">
          <UserAvatar
            pubkey={article.pubkey}
            size="lg"
            className="w-12 h-12 sm:w-14 sm:h-14 ring-2 ring-white dark:ring-black hover:ring-4 transition-all"
          />
        </Link>

        <div className="flex-1">
          <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
            <Link to={`/p/${npub}`} className="group">
              <div className="font-semibold text-lg text-neutral-900 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">
                {authorName}
              </div>
              {authorBio && (
                <p className="text-sm text-neutral-600 dark:text-neutral-400 line-clamp-1 max-w-md">
                  {authorBio}
                </p>
              )}
            </Link>

            {!isOwnArticle && currentUser && (
              <FollowButton pubkey={article.pubkey} variant="subtle" />
            )}
          </div>
        </div>
      </div>

      {/* Article Metadata */}
      <div className="flex items-center gap-2 text-sm text-neutral-500 dark:text-neutral-400">
        {publishedAt && (
          <>
            <time dateTime={new Date(publishedAt * 1000).toISOString()}>
              {new Date(publishedAt * 1000).toLocaleDateString('en-US', {
                year: 'numeric',
                month: 'long',
                day: 'numeric'
              })}
            </time>
            <span>·</span>
          </>
        )}
        <span>{readingTime} min read</span>
      </div>

      {/* Divider */}
      <div className="mt-8 border-t border-neutral-200 dark:border-neutral-800" />
    </div>
  );
}

// src/lib/components/ArticleHeader.svelte
<script lang="ts">
  import type { NDKArticle } from '@nostr-dev-kit/ndk';
  import { ndk } from '$lib/ndk.svelte';
  import { Avatar } from '@nostr-dev-kit/svelte';
  import { nip19 } from 'nostr-tools';

  interface Props {
    article: NDKArticle;
  }

  let { article }: Props = $props();

  const authorProfile = ndk.$fetchProfile(() => article.pubkey);
  const currentUser = ndk.$currentUser;
  const title = $derived(article.title || 'Untitled');
  const summary = $derived(article.summary);
  const publishedAt = $derived(article.published_at);

  const wordsPerMinute = 200;
  const readingTime = $derived.by(() => {
    const words = article.content?.split(/\s+/).length || 0;
    return Math.ceil(words / wordsPerMinute);
  });

  const authorName = $derived(authorProfile?.name || authorProfile?.displayName || 'Anonymous');
  const authorBio = $derived(authorProfile?.about);
  const isOwnArticle = $derived(currentUser?.pubkey === article.pubkey);
  const npub = $derived(nip19.npubEncode(article.pubkey));

  function navigateToProfile() {
    window.location.href = `/p/${npub}`;
  }
</script>

<div class="mb-12">
  <h1 class="text-4xl sm:text-5xl lg:text-6xl font-bold text-neutral-900 dark:text-white mb-6 leading-[1.1] tracking-tight font-serif">
    {title}
  </h1>

  {#if summary}
    <p class="text-xl sm:text-2xl text-neutral-600 dark:text-neutral-400 mb-8 leading-relaxed font-light">
      {summary}
    </p>
  {/if}

  <div class="flex items-start sm:items-center gap-4 mb-8">
    <button type="button" onclick={navigateToProfile} class="flex-shrink-0">
      <Avatar {ndk} pubkey={article.pubkey} class="w-12 h-12 sm:w-14 sm:h-14 ring-2 ring-white dark:ring-black hover:ring-4 transition-all" />
    </button>

    <div class="flex-1">
      <div class="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
        <button type="button" onclick={navigateToProfile} class="group text-left">
          <div class="font-semibold text-lg text-neutral-900 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">
            {authorName}
          </div>
          {#if authorBio}
            <p class="text-sm text-neutral-600 dark:text-neutral-400 line-clamp-1 max-w-md">
              {authorBio}
            </p>
          {/if}
        </button>
      </div>
    </div>
  </div>

  <div class="flex items-center gap-2 text-sm text-neutral-500 dark:text-neutral-400">
    {#if publishedAt}
      <time datetime={new Date(publishedAt * 1000).toISOString()}>
        {new Date(publishedAt * 1000).toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'long',
          day: 'numeric'
        })}
      </time>
      <span>·</span>
    {/if}
    <span>{readingTime} min read</span>
  </div>

  <div class="mt-8 border-t border-neutral-200 dark:border-neutral-800" />
</div>
