// src/features/articles/components/CommentCard.tsx
import { NDKEvent } from '@nostr-dev-kit/ndk';
import { useProfile } from '@nostr-dev-kit/ndk-hooks';
import { formatDistanceToNow } from 'date-fns';
import { UserAvatar } from '@/components/ui/UserAvatar';
import { ContentRenderer } from '@/components/content/ContentRenderer';

interface CommentCardProps {
  event: NDKEvent;
}

export function CommentCard({ event }: CommentCardProps) {
  const profile = useProfile(event.pubkey);
  const displayName = profile?.name || profile?.displayName || 'Anonymous';

  return (
    <div className="group">
      <div className="flex gap-3">
        <UserAvatar
          pubkey={event.pubkey}
          size="md"
          className="w-10 h-10 flex-shrink-0"
        />
        <div className="flex-1 min-w-0">
          <div className="flex items-baseline gap-2 mb-1">
            <span className="font-semibold text-neutral-900 dark:text-white">
              {displayName}
            </span>
            <span className="text-sm text-neutral-500 dark:text-neutral-400">
              {event.created_at && formatDistanceToNow(new Date(event.created_at * 1000), { addSuffix: true })}
            </span>
          </div>
          <ContentRenderer
            content={event.content.trim()}
            emojiTags={event.tags}
            event={event}
            className="text-neutral-800 dark:text-neutral-200 leading-relaxed"
          />
        </div>
      </div>
    </div>
  );
}

// src/lib/components/CommentCard.svelte
<script lang="ts">
  import type { NDKEvent } from '@nostr-dev-kit/ndk';
  import { Avatar, EventContent } from '@nostr-dev-kit/svelte';
  import { formatDistanceToNow } from 'date-fns';
  import { ndk } from '$lib/ndk.svelte';
  import { nip19 } from 'nostr-tools';

  interface Props {
    event: NDKEvent;
  }

  let { event }: Props = $props();

  const profile = ndk.$fetchProfile(() => event.pubkey);
  const displayName = $derived(profile?.name || profile?.displayName || 'Anonymous');
  const npub = $derived(nip19.npubEncode(event.pubkey));

  function navigateToProfile() {
    window.location.href = `/p/${npub}`;
  }
</script>

<div class="group">
  <div class="flex gap-3">
    <button type="button" onclick={navigateToProfile} class="flex-shrink-0">
      <Avatar {ndk} pubkey={event.pubkey} class="w-10 h-10 cursor-pointer hover:opacity-80 transition-opacity" />
    </button>
    <div class="flex-1 min-w-0">
      <div class="flex items-baseline gap-2 mb-1">
        <span class="font-semibold text-neutral-900 dark:text-white">
          {displayName}
        </span>
        {#if event.created_at}
          <span class="text-sm text-neutral-500 dark:text-neutral-400">
            {formatDistanceToNow(new Date(event.created_at * 1000), { addSuffix: true })}
          </span>
        {/if}
      </div>
      <div class="text-neutral-800 dark:text-neutral-200 leading-relaxed whitespace-pre-wrap break-words">
        <EventContent {ndk} content={event.content} emojiTags={event.tags} />
      </div>
    </div>
  </div>
</div>
