// src/features/feed/NoteCard.tsx
import { useProfile, useNDK, useNDKCurrentUser } from '@nostr-dev-kit/ndk-hooks';
import { NDKEvent, NDKKind } from '@nostr-dev-kit/ndk-hooks';
import { Heart, MessageCircle, Repeat2, Share, MoreHorizontal, Copy, Code2, ChevronDown, ChevronUp } from 'lucide-react';
import { useState, useRef, useEffect } from 'react';
import { cn } from '@/lib/utils';
import { ZapButton } from '@/components/wallet/ZapButton';
import { UserAvatar } from '@/components/ui/UserAvatar';
import { Link, useNavigate } from 'react-router-dom';
import { ContentRenderer } from '@/components/content/ContentRenderer';
import { nip19 } from 'nostr-tools';

// Custom function for abbreviated timestamps
function formatTimeAgo(timestamp: number): string {
  const now = Date.now();
  const then = timestamp * 1000;
  const seconds = Math.floor((now - then) / 1000);

  if (seconds < 60) return 'now';

  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m`;

  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h`;

  const days = Math.floor(hours / 24);
  if (days < 7) return `${days}d`;

  const weeks = Math.floor(days / 7);
  if (weeks < 4) return `${weeks}w`;

  const months = Math.floor(days / 30);
  if (months < 12) return `${months}mo`;

  const years = Math.floor(days / 365);
  return `${years}y`;
}

interface NoteCardProps {
  event: NDKEvent;
}

export function NoteCard({ event }: NoteCardProps) {
  const profile = useProfile(event.pubkey);
  const { ndk } = useNDK();
  const currentUser = useNDKCurrentUser();
  const navigate = useNavigate();
  const [isLiked, setIsLiked] = useState(false);
  const [likeCount, setLikeCount] = useState(0);
  const [dropdownOpen, setDropdownOpen] = useState(false);
  const [showRawEvent, setShowRawEvent] = useState(false);
  const [isExpanded, setIsExpanded] = useState(false);
  const [needsExpansion, setNeedsExpansion] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  // Check if this note is a reply
  const replyToTag = event.tags.find(tag =>
    tag[0] === 'e' && (tag[3] === 'reply' || tag[3] === 'root' || !tag[3])
  );
  const replyToPubkeyTag = event.tags.find(tag => tag[0] === 'p');
  const replyToPubkey = replyToPubkeyTag?.[1];
  const replyToProfile = useProfile(replyToPubkey || '');
  
  const handleLike = async () => {
    if (!currentUser || !ndk) return;
    
    try {
      const reaction = new NDKEvent(ndk);
      reaction.kind = NDKKind.Reaction;
      reaction.content = isLiked ? '-' : '+';
      reaction.tags = [
        ['e', event.id],
        ['p', event.pubkey]
      ];
      
      await reaction.publish();
      setIsLiked(!isLiked);
      setLikeCount(prev => isLiked ? prev - 1 : prev + 1);
    } catch (error) {
      console.error('Failed to publish reaction:', error);
    }
  };

  const handleRepost = async () => {
    if (!currentUser || !ndk) return;
    
    try {
      const repost = new NDKEvent(ndk);
      repost.kind = NDKKind.Repost;
      repost.content = '';
      repost.tags = [
        ['e', event.id],
        ['p', event.pubkey]
      ];
      
      await repost.publish();
    } catch (error) {
      console.error('Failed to repost:', error);
    }
  };

  const displayName = profile?.name || 'Anonymous';
  const npub = nip19.npubEncode(event.pubkey);
  const handle = profile?.nip05 ? `@${profile.nip05.split('@')[0]}` : `@${npub.slice(5, 12)}`;

  // Check if content exceeds 60vh
  useEffect(() => {
    if (contentRef.current) {
      const viewportHeight = window.innerHeight;
      const maxHeight = viewportHeight * 0.6; // 60vh
      const contentHeight = contentRef.current.scrollHeight;
      setNeedsExpansion(contentHeight > maxHeight);
    }
  }, [event.content]);

  const handleNoteClick = (e: React.MouseEvent) => {
    // Don't navigate if clicking on interactive elements
    const target = e.target as HTMLElement;
    if (
      target.closest('a') ||
      target.closest('button') ||
      target.closest('[role="button"]')
    ) {
      return;
    }

    const neventId = event.encode();
    navigate(`/e/${neventId}`);
  };

  const handleCopyId = () => {
    navigator.clipboard.writeText(event.encode());
    setDropdownOpen(false);
  };

  const handleViewRaw = () => {
    setShowRawEvent(true);
    setDropdownOpen(false);
  };

  return (
    <>
    <article
      className="bg-white dark:bg-black border-b border-gray-100 dark:border-gray-800 hover:bg-gray-50/50 dark:hover:bg-gray-800/50 transition-all duration-150 cursor-pointer"
      onClick={handleNoteClick}>
      <div className="px-4 py-3 sm:px-5 sm:py-4 relative">
        {/* Timestamp in top right corner */}
        <time
          className="absolute top-3 right-4 sm:top-4 sm:right-5 text-gray-500 dark:text-gray-400 text-[13px] sm:text-sm hover:underline cursor-help"
          title={new Date(event.created_at! * 1000).toLocaleString()}
        >
          {formatTimeAgo(event.created_at!)}
        </time>

        {/* Mobile: Stack layout, Desktop: Side-by-side */}
        <div className="flex flex-col sm:flex-row sm:gap-3">
          {/* Mobile header (avatar + author info) */}
          <div className="flex items-start gap-3 mb-2 sm:hidden">
            <Link to={`/p/${npub}`} className="flex-shrink-0">
              <UserAvatar
                pubkey={event.pubkey}
                size="md"
                className="w-10 h-10 ring-1 ring-neutral-200/50 dark:ring-neutral-800/50 shadow-soft"
              />
            </Link>
            <div className="flex-1 min-w-0 pr-24">
              <Link
                to={`/p/${npub}`}
                className="flex items-center gap-1 hover:opacity-75 transition-opacity"
              >
                <span className="font-medium text-[15px] text-gray-900 dark:text-white whitespace-nowrap">
                  {displayName}
                </span>
                <span className="text-gray-500 dark:text-gray-400 text-[13px] whitespace-nowrap">
                  {handle}
                </span>
              </Link>
            </div>
          </div>

          {/* Desktop avatar */}
          <Link to={`/p/${npub}`} className="hidden sm:block flex-shrink-0">
            <UserAvatar
              pubkey={event.pubkey}
              size="md"
              className="w-11 h-11 ring-1 ring-neutral-200/50 dark:ring-neutral-800/50 shadow-soft"
            />
          </Link>

          {/* Content */}
          <div className="flex-1 min-w-0">
            {/* Desktop author info */}
            <div className="hidden sm:flex items-center gap-2 pr-32">
              <Link
                to={`/p/${npub}`}
                className="flex items-center gap-1.5 hover:opacity-75 transition-opacity min-w-0"
              >
                <span className="font-medium text-base text-gray-900 dark:text-white whitespace-nowrap">
                  {displayName}
                </span>
                <span className="text-gray-500 dark:text-gray-400 text-sm whitespace-nowrap">
                  {handle}
                </span>
              </Link>
            </div>

            {/* Reply indicator */}
            {replyToTag && replyToPubkey && (
              <div className="flex items-center gap-1 mt-1 text-sm text-gray-500 dark:text-gray-400">
                <span>Replying to</span>
                <Link
                  to={`/p/${nip19.npubEncode(replyToPubkey)}`}
                  className="font-medium hover:underline text-gray-700 dark:text-gray-300"
                >
                  @{replyToProfile?.name || replyToProfile?.displayName || `${replyToPubkey?.slice(0, 8)}...`}
                </Link>
              </div>
            )}

            {/* Note content */}
            <div className="mt-2 relative">
              <div
                ref={contentRef}
                className={cn(
                  "overflow-hidden transition-all duration-300",
                  !isExpanded && needsExpansion && "max-h-[60vh]"
                )}
              >
                <ContentRenderer
                  content={event.content}
                  className="text-gray-800 dark:text-gray-200 text-[15px] sm:text-base leading-relaxed"
                />
                {/* Gradient fade when collapsed */}
                {!isExpanded && needsExpansion && (
                  <div className="absolute bottom-0 left-0 right-0 h-24 bg-gradient-to-t from-white dark:from-gray-900 to-transparent pointer-events-none" />
                )}
              </div>

              {/* Read More/Less Button */}
              {needsExpansion && (
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    setIsExpanded(!isExpanded);
                  }}
                  className="mt-3 flex items-center gap-1.5 px-4 py-2 bg-gray-900 dark:bg-white text-white dark:text-gray-900 text-sm font-medium rounded-full hover:bg-gray-800 dark:hover:bg-gray-100 transition-all duration-200"
                >
                  <span>{isExpanded ? 'Read Less' : 'Read More'}</span>
                  {isExpanded ? (
                    <ChevronUp className="w-4 h-4" />
                  ) : (
                    <ChevronDown className="w-4 h-4" />
                  )}
                </button>
              )}
            </div>

            {/* Action buttons */}
            <div className="flex items-center justify-between mt-4 -ml-2">
              <div className="flex items-center gap-1">
                <button
                  onClick={() => {/* TODO: Implement reply */}}
                  className="group flex items-center gap-1.5 p-2.5 rounded-lg hover:bg-neutral-100 dark:hover:bg-neutral-800/50 transition-all duration-200"
                  disabled={!currentUser}
                >
                  <MessageCircle className="w-4 h-4 text-neutral-500 group-hover:text-gray-700 dark:text-neutral-500 dark:group-hover:text-gray-300" strokeWidth={1.5} />
                  {/* Reply count will be shown when implemented */}
                </button>

                <button
                  onClick={handleRepost}
                  className="group flex items-center gap-1.5 p-2.5 rounded-lg hover:bg-neutral-100 dark:hover:bg-neutral-800/50 transition-all duration-200"
                  disabled={!currentUser}
                >
                  <Repeat2 className="w-4 h-4 text-neutral-500 group-hover:text-success-600 dark:text-neutral-500 dark:group-hover:text-success-400" strokeWidth={1.5} />
                  {/* Repost count will be shown when implemented */}
                </button>

                <button
                  onClick={handleLike}
                  className={cn(
                    "group flex items-center gap-1.5 p-2.5 rounded-lg transition-all duration-200",
                    isLiked
                      ? "bg-danger-50 dark:bg-danger-950/20"
                      : "hover:bg-neutral-100 dark:hover:bg-neutral-800/50"
                  )}
                  disabled={!currentUser}
                >
                  <Heart
                    className={cn(
                      "w-4 h-4 transition-all duration-200",
                      isLiked
                        ? "fill-current text-danger-500 dark:text-danger-400"
                        : "text-neutral-500 group-hover:text-danger-500 dark:text-neutral-500 dark:group-hover:text-danger-400"
                    )}
                    strokeWidth={1.5}
                  />
                  {likeCount > 0 && (
                    <span className={cn(
                      "text-sm font-medium",
                      isLiked
                        ? "text-pink-500 dark:text-pink-400"
                        : "text-gray-500 group-hover:text-pink-500 dark:text-gray-400 dark:group-hover:text-pink-400"
                    )}>
                      {likeCount}
                    </span>
                  )}
                </button>

                {/* Zap Button */}
                <ZapButton
                  eventId={event.id}
                  authorPubkey={event.pubkey}
                  onZap={(amount) => console.log(`Zapped ${amount} sats to`, event.pubkey)}
                />

                <button
                  onClick={() => {/* TODO: Implement share */}}
                  className="group p-2.5 rounded-lg hover:bg-neutral-100 dark:hover:bg-neutral-800/50 transition-all duration-200"
                >
                  <Share className="w-4 h-4 text-neutral-500 group-hover:text-gray-700 dark:text-neutral-500 dark:group-hover:text-gray-300" strokeWidth={1.5} />
                </button>
              </div>

              <div className="relative">
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    setDropdownOpen(!dropdownOpen);
                  }}
                  className="p-2 rounded-lg hover:bg-neutral-100 dark:hover:bg-neutral-800/50 transition-all duration-200"
                >
                  <MoreHorizontal className="w-4 h-4 text-neutral-400 dark:text-neutral-600" strokeWidth={1.5} />
                </button>

                {dropdownOpen && (
                  <div className="absolute right-0 mt-2 w-48 bg-white dark:bg-gray-800 rounded-lg shadow-lg border border-gray-200 dark:border-gray-700 z-50">
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleCopyId();
                      }}
                      className="w-full px-4 py-2 text-left text-sm hover:bg-gray-50 dark:hover:bg-gray-700 flex items-center gap-2 rounded-t-lg"
                    >
                      <Copy className="w-4 h-4" />
                      Copy ID
                    </button>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleViewRaw();
                      }}
                      className="w-full px-4 py-2 text-left text-sm hover:bg-gray-50 dark:hover:bg-gray-700 flex items-center gap-2 rounded-b-lg"
                    >
                      <Code2 className="w-4 h-4" />
                      View Raw Event
                    </button>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </article>

    {/* Raw Event Modal */}
    {showRawEvent && (
      <>
        <div
          className="fixed inset-0 bg-black/50 z-50"
          onClick={() => setShowRawEvent(false)}
        />
        <div className="fixed inset-4 md:inset-auto md:top-1/2 md:left-1/2 md:-translate-x-1/2 md:-translate-y-1/2 md:max-w-2xl md:w-full z-50">
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl h-full md:h-auto max-h-[80vh] flex flex-col">
            <div className="flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-700">
              <h3 className="text-lg font-semibold">Raw Event</h3>
              <button
                onClick={() => setShowRawEvent(false)}
                className="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <div className="p-4 overflow-auto flex-1">
              <pre className="text-xs font-mono whitespace-pre-wrap break-all bg-gray-50 dark:bg-black p-4 rounded-lg">
                <code className="language-json">
                  {event.inspect}
                </code>
              </pre>
            </div>
          </div>
        </div>
      </>
    )}
    </>
  );
}

// src/lib/components/NoteCard.svelte
<script lang="ts">
  import type { NDKEvent } from '@nostr-dev-kit/ndk';
  import { ndk } from '$lib/ndk.svelte';
  import { Avatar, EventContent } from '@nostr-dev-kit/svelte';
  import { toast } from '$lib/stores/toast.svelte';
  import * as Dialog from '$lib/components/ui/dialog';
  import { Button } from '$lib/components/ui/button';
  import ReplyIndicator from './ReplyIndicator.svelte';
  import RelayBadge from './RelayBadge.svelte';
  import UserHoverCard from './UserHoverCard.svelte';
  import TimeAgo from './TimeAgo.svelte';
  import EventActions from './EventActions.svelte';

  interface Props {
    event: NDKEvent;
    showActions?: boolean;
    variant?: 'default' | 'thread-parent' | 'thread-main' | 'thread-reply';
    showThreadLine?: boolean;
    onNavigate?: () => void;
  }

  const {
    event,
    showActions = true,
    variant = 'default',
    showThreadLine = false,
    onNavigate
  }: Props = $props();

  const profile = ndk.$fetchProfile(() => event.pubkey);
  const npub = $derived(event.author.npub);

  let showOptionsMenu = $state(false);
  let showRawEventModal = $state(false);
  let showUserHoverCard = $state(false);
  let hoverCardPosition = $state({ x: 0, y: 0 });
  let hoverTimer: ReturnType<typeof setTimeout> | null = null;
  let avatarElement = $state<HTMLButtonElement | null>(null);

  function navigateToProfile() {
    window.location.href = `/p/${npub}`;
  }

  function navigateToEvent() {
    if (onNavigate) {
      onNavigate();
      return;
    }
    // Encode the event as a nevent
    const neventId = event.encode();
    window.location.href = `/e/${neventId}`;
  }

  const avatarSize = $derived(
    variant === 'thread-main' ? 'w-14 h-14' :
    variant === 'thread-reply' ? 'w-10 h-10' :
    'w-9 h-9 sm:w-12 sm:h-12'
  );

  const textSize = $derived(
    variant === 'thread-main' ? 'text-lg leading-relaxed' : 'text-base'
  );

  const nameSize = $derived(
    variant === 'thread-main' ? 'text-lg font-bold' : 'text-base font-semibold'
  );

  const bgClass = $derived(
    variant === 'thread-main' ? 'bg-card/50' :
    variant === 'default' ? 'hover:bg-card/30' :
    'hover:bg-card/30'
  );

  const clickable = $derived(variant === 'default' || (onNavigate !== undefined));

  async function copyToClipboard(text: string, label: string) {
    try {
      await navigator.clipboard.writeText(text);
      toast.success(`Copied ${label}`);
    } catch (err) {
      console.error('Failed to copy:', err);
      toast.error(`Failed to copy ${label}`);
    }
    showOptionsMenu = false;
  }

  function copyAuthorNprofile() {
    const nprofile = event.author.nprofile();
    copyToClipboard(nprofile, 'author nprofile');
  }

  function copyEventId() {
    const nevent = event.encode();
    copyToClipboard(nevent, 'event ID');
  }

  function copyRawEvent() {
    const raw = event.inspect;
    copyToClipboard(raw, 'raw event');
  }

  function viewRawEvent() {
    showOptionsMenu = false;
    showRawEventModal = true;
  }

  function handleAvatarMouseEnter(e: MouseEvent) {
    if (hoverTimer) clearTimeout(hoverTimer);

    hoverTimer = setTimeout(() => {
      if (avatarElement) {
        const rect = avatarElement.getBoundingClientRect();
        const viewportWidth = window.innerWidth;
        const cardWidth = 320; // w-80 = 320px
        const spacing = 16;

        // Calculate horizontal position
        let x = rect.right + spacing;

        // If card would overflow right edge, position to the left
        if (x + cardWidth > viewportWidth - spacing) {
          x = rect.left - cardWidth - spacing;
        }

        // Vertical position - align with top of avatar
        const y = rect.top;

        hoverCardPosition = { x, y };
        showUserHoverCard = true;
      }
    }, 500);
  }

  function handleAvatarMouseLeave(e: MouseEvent) {
    if (hoverTimer) {
      clearTimeout(hoverTimer);
      hoverTimer = null;
    }

    // Don't hide if moving to the hover card
    hoverTimer = setTimeout(() => {
      showUserHoverCard = false;
    }, 100);
  }

  function handleHoverCardMouseEnter() {
    // Cancel the hide timer when entering the card
    if (hoverTimer) {
      clearTimeout(hoverTimer);
      hoverTimer = null;
    }
  }

  function handleHoverCardMouseLeave() {
    showUserHoverCard = false;
  }

  $effect(() => {
    if (!showOptionsMenu) return;

    const handleClickOutside = () => {
      showOptionsMenu = false;
    };

    document.addEventListener('click', handleClickOutside);
    return () => document.removeEventListener('click', handleClickOutside);
  });
</script>

<article
  class="p-3 sm:p-4 max-sm:max-w-screen {bgClass} transition-colors {clickable ? 'cursor-pointer' : ''} border-b border-border relative min-w-0"
  onclick={clickable ? navigateToEvent : undefined}
  role={clickable ? 'button' : undefined}
  tabindex={clickable ? 0 : undefined}
>
  {#if showThreadLine}
    <div class="absolute left-[29px] -top-px h-[73px] w-0.5 bg-muted"></div>
    <div class="absolute left-[29px] top-[73px] bottom-0 w-0.5 bg-muted"></div>
  {/if}

  <!-- Header Row: Avatar + Name/Handle/Time -->
  <div class="flex items-center gap-2 sm:gap-3 {variant === 'thread-main' ? 'mb-2' : 'mb-1.5'}">
    <button
      bind:this={avatarElement}
      type="button"
      onclick={(e) => { e.stopPropagation(); navigateToProfile(); }}
      onmouseenter={handleAvatarMouseEnter}
      onmouseleave={handleAvatarMouseLeave}
      class="flex-shrink-0"
    >
      <Avatar {ndk} pubkey={event.pubkey} class={`${avatarSize} cursor-pointer hover:opacity-80 transition-opacity`} />
    </button>

    <div class="flex items-center gap-2 flex-1 min-w-0">
      <div class="flex items-center gap-2 min-w-0 flex-shrink">
        <span class={`${nameSize} text-foreground truncate min-w-0`}>
          {profile?.displayName || profile?.name || `${event.pubkey.slice(0, 8)}...`}
        </span>
        {#if variant === 'default' || variant === 'thread-reply'}
          <span class="text-muted-foreground text-sm truncate min-w-0">
            @{profile?.name || event.pubkey.slice(0, 8)}
          </span>
        {/if}
      </div>
      <span class="text-muted-foreground text-sm flex-shrink-0">·</span>
      {#if event.created_at}
        <TimeAgo timestamp={event.created_at} class="text-muted-foreground text-sm flex-shrink-0" />
      {/if}
    </div>

    <div class="relative flex-shrink-0">
      <button
        onclick={(e) => { e.stopPropagation(); showOptionsMenu = !showOptionsMenu; }}
        class="p-1 hover:bg-muted rounded-full transition-colors"
        type="button"
        aria-label="More options"
      >
        <svg class="w-5 h-5 text-muted-foreground" fill="currentColor" viewBox="0 0 24 24">
          <path d="M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z"/>
        </svg>
      </button>

      {#if showOptionsMenu}
        <div
          class="absolute right-0 mt-1 w-72 bg-popover border border-border rounded-lg shadow-lg z-10 max-h-96 overflow-y-auto"
          onclick={(e) => e.stopPropagation()}
        >
          <button
            onclick={copyAuthorNprofile}
            class="w-full px-4 py-2 text-left text-sm text-foreground hover:bg-muted transition-colors first:rounded-t-lg"
            type="button"
          >
            Copy author (nprofile)
          </button>
          <button
            onclick={copyEventId}
            class="w-full px-4 py-2 text-left text-sm text-foreground hover:bg-muted transition-colors"
            type="button"
          >
            Copy ID (nevent)
          </button>
          <button
            onclick={copyRawEvent}
            class="w-full px-4 py-2 text-left text-sm text-foreground hover:bg-muted transition-colors"
            type="button"
          >
            Copy raw event
          </button>
          <button
            onclick={viewRawEvent}
            class="w-full px-4 py-2 text-left text-sm text-foreground hover:bg-muted transition-colors"
            type="button"
          >
            View raw event
          </button>

          {#if event.onRelays && event.onRelays.size > 0}
            <div class="border-t border-border mt-1 pt-1">
              <div class="px-4 py-2 text-xs text-muted-foreground font-medium">
                Seen on {event.onRelays.size} relay{event.onRelays.size === 1 ? '' : 's'}
              </div>
              <div class="px-2 pb-2 space-y-1">
                {#each Array.from(event.onRelays) as relay (relay.url)}
                  <RelayBadge {relay} variant="compact" />
                {/each}
              </div>
            </div>
          {/if}
        </div>
      {/if}
    </div>
  </div>

  <!-- Reply indicator -->
  {#if variant === 'default'}
    <ReplyIndicator {event} />
  {/if}

  <!-- Content -->
  <div class="text-foreground whitespace-pre-wrap break-words {textSize} mb-2 overflow-hidden">
    <EventContent {ndk} event={event} />
  </div>

  <!-- Actions -->
  {#if showActions}
    <EventActions {event} variant={variant} />
  {/if}
</article>

<!-- User Hover Card -->
<div
  onmouseenter={handleHoverCardMouseEnter}
  onmouseleave={handleHoverCardMouseLeave}
>
  <UserHoverCard
    pubkey={event.pubkey}
    isVisible={showUserHoverCard}
    position={hoverCardPosition}
  />
</div>

<!-- Raw Event Modal -->
<Dialog.Root bind:open={showRawEventModal}>
  <Dialog.Content class="max-w-4xl max-h-[80vh] overflow-hidden flex flex-col">
    <Dialog.Header>
      <Dialog.Title>Raw Event</Dialog.Title>
      <Dialog.Description>
        JSON representation of this Nostr event
      </Dialog.Description>
    </Dialog.Header>

    <div class="flex-1 overflow-auto bg-muted/50 rounded-lg p-4 font-mono text-sm">
      <pre class="whitespace-pre-wrap break-words">{event.inspect()}</pre>
    </div>

    <div class="flex justify-end gap-2 pt-4">
      <Button
        variant="outline"
        onclick={() => copyToClipboard(event.inspect(), 'raw event')}
      >
        Copy to Clipboard
      </Button>
      <Button onclick={() => showRawEventModal = false}>
        Close
      </Button>
    </div>
  </Dialog.Content>
</Dialog.Root>
