// src/lib/components/TimeAgo.svelte
<script lang="ts">
  import { formatTimeAgo } from '$lib/utils/formatTime';

  interface Props {
    timestamp: number;
    class?: string;
  }

  const { timestamp, class: className = '' }: Props = $props();

  let formattedTime = $state(formatTimeAgo(timestamp));

  // Calculate update interval based on how old the timestamp is
  function getUpdateInterval(ts: number): number {
    const now = Date.now();
    const diff = now - (ts * 1000);
    const seconds = Math.floor(diff / 1000);

    if (seconds < 60) {
      return 1000; // Update every second for "just now"
    } else if (seconds < 3600) {
      return 60000; // Update every minute for minutes
    } else if (seconds < 86400) {
      return 3600000; // Update every hour for hours
    } else {
      return 86400000; // Update every day for days and beyond
    }
  }

  function updateTime() {
    formattedTime = formatTimeAgo(timestamp);
  }

  $effect(() => {
    // Set up interval to update the time
    const interval = getUpdateInterval(timestamp);
    const intervalId = setInterval(updateTime, interval);

    return () => {
      clearInterval(intervalId);
    };
  });
</script>

<time datetime={new Date(timestamp * 1000).toISOString()} class={className} title={new Date(timestamp * 1000).toLocaleString()}>
  {formattedTime}
</time>

// src/components/ui/TimeAgo.tsx
import { useEffect, useState } from 'react';

interface TimeAgoProps {
  timestamp: number;
  className?: string;
}

export function TimeAgo({ timestamp, className = '' }: TimeAgoProps) {
  const [timeAgo, setTimeAgo] = useState('');

  useEffect(() => {
    const calculateTimeAgo = () => {
      const now = Date.now() / 1000;
      const diff = now - timestamp;

      if (diff < 60) {
        return 'just now';
      } else if (diff < 3600) {
        const minutes = Math.floor(diff / 60);
        return `${minutes}m`;
      } else if (diff < 86400) {
        const hours = Math.floor(diff / 3600);
        return `${hours}h`;
      } else if (diff < 604800) {
        const days = Math.floor(diff / 86400);
        return `${days}d`;
      } else if (diff < 2592000) {
        const weeks = Math.floor(diff / 604800);
        return `${weeks}w`;
      } else if (diff < 31536000) {
        const months = Math.floor(diff / 2592000);
        return `${months}mo`;
      } else {
        const years = Math.floor(diff / 31536000);
        return `${years}y`;
      }
    };

    setTimeAgo(calculateTimeAgo());

    // Update every minute
    const interval = setInterval(() => {
      setTimeAgo(calculateTimeAgo());
    }, 60000);

    return () => clearInterval(interval);
  }, [timestamp]);

  return <span className={className}>{timeAgo}</span>;
}
